QBCore.Shared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBCore.Shared.Jobs = {
	unemployed = { label = 'Sivil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Serbest Çalışan', payment = 10 } } },
	bus = { label = 'Otobüs', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Şoför', payment = 50 } } },
	judge = { label = 'Onursal', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Hakim', payment = 100 } } },
	lawyer = { label = 'Hukuk Bürosu', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Avukat', payment = 50 } } },
	reporter = { label = 'Muhabir', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Gazeteci', payment = 50 } } },
	trucker = { label = 'Tır Şoförü', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Şoför', payment = 50 } } },
	tow = { label = 'Çekici', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Şoför', payment = 50 } } },
	garbage = { label = 'Çöp Toplama', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Toplayıcı', payment = 50 } } },
	vineyard = { label = 'Bağcılık', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Toplayıcı', payment = 50 } } },
	hotdog = { label = 'Sosisli', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Satış', payment = 50 } } },

	police = {
		label = 'Kolluk Kuvvetleri',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Memur', payment = 75 },
			['2'] = { name = 'Çavuş', payment = 100 },
			['3'] = { name = 'Teğmen', payment = 125 },
			['4'] = { name = 'Şef', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'Acil Sağlık',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Paramedik', payment = 75 },
			['2'] = { name = 'Doktor', payment = 100 },
			['3'] = { name = 'Cerrah', payment = 125 },
			['4'] = { name = 'Şef', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Emlak',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Ev Satışı', payment = 75 },
			['2'] = { name = 'İşyeri Satışı', payment = 100 },
			['3'] = { name = 'Emlakçı', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taksi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Şoför', payment = 75 },
			['2'] = { name = 'Etkinlik Şoförü', payment = 100 },
			['3'] = { name = 'Satış', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Araç Galerisi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Showroom Satışı', payment = 75 },
			['2'] = { name = 'İşyeri Satışı', payment = 100 },
			['3'] = { name = 'Finans', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Çırak', payment = 75 },
			['2'] = { name = 'Deneyimli', payment = 100 },
			['3'] = { name = 'Usta', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Çırak', payment = 75 },
			['2'] = { name = 'Deneyimli', payment = 100 },
			['3'] = { name = 'Usta', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Çırak', payment = 75 },
			['2'] = { name = 'Deneyimli', payment = 100 },
			['3'] = { name = 'Usta', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Çırak', payment = 75 },
			['2'] = { name = 'Deneyimli', payment = 100 },
			['3'] = { name = 'Usta', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Acemi', payment = 50 },
			['1'] = { name = 'Çırak', payment = 75 },
			['2'] = { name = 'Deneyimli', payment = 100 },
			['3'] = { name = 'Usta', payment = 125 },
			['4'] = { name = 'Müdür', isboss = true, payment = 150 },
		},
	},
}
