QBCore.Shared.Weapons = {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`]               = { name = 'weapon_unarmed', label = 'Yumruklar', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_dagger`]                = { name = 'weapon_dagger', label = 'Hançer', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_bat`]                   = { name = 'weapon_bat', label = 'Sopa', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_bottle`]                = { name = 'weapon_bottle', label = 'Kırık Şişe', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_crowbar`]               = { name = 'weapon_crowbar', label = 'Levye', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_flashlight`]            = { name = 'weapon_flashlight', label = 'El Feneri', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_golfclub`]              = { name = 'weapon_golfclub', label = 'Golf Sopası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_hammer`]                = { name = 'weapon_hammer', label = 'Çekiç', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_hatchet`]               = { name = 'weapon_hatchet', label = 'Balta', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_knuckle`]               = { name = 'weapon_knuckle', label = 'Muşta', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_knife`]                 = { name = 'weapon_knife', label = 'Bıçak', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_machete`]               = { name = 'weapon_machete', label = 'Pala', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_switchblade`]           = { name = 'weapon_switchblade', label = 'Çakı', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_nightstick`]            = { name = 'weapon_nightstick', label = 'Cop Sopası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_wrench`]                = { name = 'weapon_wrench', label = 'İngiliz Anahtarı', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_battleaxe`]             = { name = 'weapon_battleaxe', label = 'Savaş Baltası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_poolcue`]               = { name = 'weapon_poolcue', label = 'Bilardo Istakası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_briefcase`]             = { name = 'weapon_briefcase', label = 'Evrak Çantası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_briefcase_02`]          = { name = 'weapon_briefcase_02', label = 'Evrak Çantası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_garbagebag`]            = { name = 'weapon_garbagebag', label = 'Çöp Torbası', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_handcuffs`]             = { name = 'weapon_handcuffs', label = 'Kelepçe', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_bread`]                 = { name = 'weapon_bread', label = 'Baget', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı' },
	[`weapon_stone_hatchet`]         = { name = 'weapon_stone_hatchet', label = 'Taş Balta', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Bıçaklandı / Saplandı / Parçalandı' },
	[`weapon_candycane`]             = { name = 'weapon_candycane', label = 'Şeker Kamışı', weapontype = 'Yakın Dövüş', ammotype = nil, damagereason = 'Yakın dövüşle öldürüldü / Dayak yedi / İnfaz edildi / Dövüldü / Cinayete kurban gitti / Parçalandı / Şeker kamışıyla dövüldü' },

	-- Handguns
	[`weapon_pistol`]                = { name = 'weapon_pistol', label = 'Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_pistol_mk2`]            = { name = 'weapon_pistol_mk2', label = 'Tabanca Mk2', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_combatpistol`]          = { name = 'weapon_combatpistol', label = 'Savaş Tabancası', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_appistol`]              = { name = 'weapon_appistol', label = 'AP Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_stungun`]               = { name = 'weapon_stungun', label = 'Taser', weapontype = 'Tabanca', ammotype = 'AMMO_STUNGUN', damagereason = 'Öldü' },
	[`weapon_pistol50`]              = { name = 'weapon_pistol50', label = 'Tabanca .50 Kalibre', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_snspistol`]             = { name = 'weapon_snspistol', label = 'SNS Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_snspistol_mk2`]         = { name = 'weapon_snspistol_mk2', label = 'SNS Tabanca MK2', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_heavypistol`]           = { name = 'weapon_heavypistol', label = 'Ağır Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_vintagepistol`]         = { name = 'weapon_vintagepistol', label = 'Klasik Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_flaregun`]              = { name = 'weapon_flaregun', label = 'İşaret Fişeği Tabancası', weapontype = 'Tabanca', ammotype = 'AMMO_FLARE', damagereason = 'Öldü' },
	[`weapon_marksmanpistol`]        = { name = 'weapon_marksmanpistol', label = 'Nişancı Tabancası', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_revolver`]              = { name = 'weapon_revolver', label = 'Altıpatlar', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_revolver_mk2`]          = { name = 'weapon_revolver_mk2', label = 'Altıpatlar MK2', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_doubleaction`]          = { name = 'weapon_doubleaction', label = 'Çift Etkili Altıpatlar', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_raypistol`]             = { name = 'weapon_raypistol', label = 'Işın Tabancası', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_ceramicpistol`]         = { name = 'weapon_ceramicpistol', label = 'Seramik Tabanca', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_navyrevolver`]          = { name = 'weapon_navyrevolver', label = 'Denizci Altıpatları', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_gadgetpistol`]          = { name = 'weapon_gadgetpistol', label = 'Alet Tabancası', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },
	[`weapon_stungun_mp`]            = { name = 'weapon_stungun_mp', label = 'Taser', weapontype = 'Tabanca', ammotype = 'AMMO_STUNGUN', damagereason = 'Öldü' },
	[`weapon_pistolxm3`]             = { name = 'weapon_pistolxm3', label = 'Tabanca XM3', weapontype = 'Tabanca', ammotype = 'AMMO_PISTOL', damagereason = 'Tabancayla vuruldu / Patlattı / Deldi / Kurşunladı' },

	-- Submachine Guns
	[`weapon_microsmg`]              = { name = 'weapon_microsmg', label = 'Mikro Hafif Makineli', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_smg`]                   = { name = 'weapon_smg', label = 'Hafif Makineli', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_smg_mk2`]               = { name = 'weapon_smg_mk2', label = 'Hafif Makineli MK2', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_assaultsmg`]            = { name = 'weapon_assaultsmg', label = 'Saldırı Hafif Makineli', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_combatpdw`]             = { name = 'weapon_combatpdw', label = 'Savaş PDW', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_machinepistol`]         = { name = 'weapon_machinepistol', label = 'Tec-9', weapontype = 'Hafif Makineli', ammotype = 'AMMO_PISTOL', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_minismg`]               = { name = 'weapon_minismg', label = 'Mini Hafif Makineli', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },
	[`weapon_raycarbine`]            = { name = 'weapon_raycarbine', label = 'Işın Karabinası', weapontype = 'Hafif Makineli', ammotype = 'AMMO_SMG', damagereason = 'Delik deşik edildi / Tarandı / Avlandı / Hafif makineliyle vuruldu' },

	-- Shotguns
	[`weapon_pumpshotgun`]           = { name = 'weapon_pumpshotgun', label = 'Pompalı Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_pumpshotgun_mk2`]       = { name = 'weapon_pumpshotgun_mk2', label = 'Pompalı Av Tüfeği MK2', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_sawnoffshotgun`]        = { name = 'weapon_sawnoffshotgun', label = 'Kısa Namlulu Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_assaultshotgun`]        = { name = 'weapon_assaultshotgun', label = 'Saldırı Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_bullpupshotgun`]        = { name = 'weapon_bullpupshotgun', label = 'Bullpup Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_musket`]                = { name = 'weapon_musket', label = 'Tüfek', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_heavyshotgun`]          = { name = 'weapon_heavyshotgun', label = 'Ağır Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_dbshotgun`]             = { name = 'weapon_dbshotgun', label = 'Çift Namlulu Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_autoshotgun`]           = { name = 'weapon_autoshotgun', label = 'Otomatik Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },
	[`weapon_combatshotgun`]         = { name = 'weapon_combatshotgun', label = 'Savaş Av Tüfeği', weapontype = 'Av Tüfeği', ammotype = 'AMMO_SHOTGUN', damagereason = 'Mahvetti / Parçaladı / Av tüfeğiyle vuruldu' },

	-- Assault Rifles
	[`weapon_assaultrifle`]          = { name = 'weapon_assaultrifle', label = 'Saldırı Tüfeği', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_assaultrifle_mk2`]      = { name = 'weapon_assaultrifle_mk2', label = 'Saldırı Tüfeği MK2', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_carbinerifle`]          = { name = 'weapon_carbinerifle', label = 'Karabina Tüfeği', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_carbinerifle_mk2`]      = { name = 'weapon_carbinerifle_mk2', label = 'Karabina Tüfeği MK2', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_advancedrifle`]         = { name = 'weapon_advancedrifle', label = 'Gelişmiş Tüfek', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_specialcarbine`]        = { name = 'weapon_specialcarbine', label = 'Özel Karabina', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_specialcarbine_mk2`]    = { name = 'weapon_specialcarbine_mk2', label = 'Özel Karabina MK2', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_bullpuprifle`]          = { name = 'weapon_bullpuprifle', label = 'Bullpup Tüfek', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_bullpuprifle_mk2`]      = { name = 'weapon_bullpuprifle_mk2', label = 'Bullpup Tüfek MK2', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_compactrifle`]          = { name = 'weapon_compactrifle', label = 'Kompakt Tüfek', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_militaryrifle`]         = { name = 'weapon_militaryrifle', label = 'Askeri Tüfek', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },
	[`weapon_heavyrifle`]            = { name = 'weapon_heavyrifle', label = 'Ağır Tüfek', weapontype = 'Saldırı Tüfeği', ammotype = 'AMMO_RIFLE', damagereason = 'Öldürdü / Tüfekle vurdu / İndirdi / Yere serdi' },

	-- Light Machine Guns
	[`weapon_mg`]                    = { name = 'weapon_mg', label = 'Makineli Tüfek', weapontype = 'Hafif Makineli Tüfek', ammotype = 'AMMO_MG', damagereason = 'Makineli tüfekle vuruldu / Tarandı / Mahvetti' },
	[`weapon_combatmg`]              = { name = 'weapon_combatmg', label = 'Savaş Makineli Tüfeği', weapontype = 'Hafif Makineli Tüfek', ammotype = 'AMMO_MG', damagereason = 'Makineli tüfekle vuruldu / Tarandı / Mahvetti' },
	[`weapon_combatmg_mk2`]          = { name = 'weapon_combatmg_mk2', label = 'Savaş Makineli Tüfeği MK2', weapontype = 'Hafif Makineli Tüfek', ammotype = 'AMMO_MG', damagereason = 'Makineli tüfekle vuruldu / Tarandı / Mahvetti' },
	[`weapon_gusenberg`]             = { name = 'weapon_gusenberg', label = 'Thompson Hafif Makineli', weapontype = 'Hafif Makineli Tüfek', ammotype = 'AMMO_MG', damagereason = 'Makineli tüfekle vuruldu / Tarandı / Mahvetti' },

	-- Sniper Rifles
	[`weapon_sniperrifle`]           = { name = 'weapon_sniperrifle', label = 'Keskin Nişancı Tüfeği', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },
	[`weapon_heavysniper`]           = { name = 'weapon_heavysniper', label = 'Ağır Keskin Nişancı Tüfeği', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },
	[`weapon_heavysniper_mk2`]       = { name = 'weapon_heavysniper_mk2', label = 'Ağır Keskin Nişancı Tüfeği MK2', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },
	[`weapon_marksmanrifle`]         = { name = 'weapon_marksmanrifle', label = 'Nişancı Tüfeği', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },
	[`weapon_marksmanrifle_mk2`]     = { name = 'weapon_marksmanrifle_mk2', label = 'Nişancı Tüfeği MK2', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },
	[`weapon_remotesniper`]          = { name = 'weapon_remotesniper', label = 'Uzaktan Keskin Nişancı', weapontype = 'Keskin Nişancı Tüfeği', ammotype = 'AMMO_SNIPER_REMOTE', damagereason = 'Keskin nişancıyla vuruldu / Avladı / Dürbünlü silahla vurdu' },

	-- Heavy Weapons
	[`weapon_rpg`]                   = { name = 'weapon_rpg', label = 'RPG', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_RPG', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_grenadelauncher`]       = { name = 'weapon_grenadelauncher', label = 'Bombaatar', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_grenadelauncher_smoke`] = { name = 'weapon_grenadelauncher_smoke', label = 'Duman Bombası Fırlatıcısı', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_minigun`]               = { name = 'weapon_minigun', label = 'Minigun', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_MINIGUN', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_firework`]              = { name = 'weapon_firework', label = 'Havai Fişek Fırlatıcısı', weapontype = 'Ağır Silahlar', ammotype = nil, damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_railgun`]               = { name = 'weapon_railgun', label = 'Raylı Top', weapontype = 'Ağır Silahlar', ammotype = nil, damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_railgunxm3`]            = { name = 'weapon_railgunxm3', label = 'Raylı Top XM3', weapontype = 'Ağır Silahlar', ammotype = nil, damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_hominglauncher`]        = { name = 'weapon_hominglauncher', label = 'Güdümlü Füze Fırlatıcısı', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_STINGER', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_compactlauncher`]       = { name = 'weapon_compactlauncher', label = 'Kompakt Fırlatıcı', weapontype = 'Ağır Silahlar', ammotype = nil, damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_rayminigun`]            = { name = 'weapon_rayminigun', label = 'Işın Minigun', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_MINIGUN', damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_emplauncher`]           = { name = 'weapon_emplauncher', label = 'EMP Fırlatıcısı', weapontype = 'Ağır Silahlar', ammotype = 'AMMO_EMPLAUNCHER', damagereason = 'Öldü' },

	-- Throwables
	[`weapon_grenade`]               = { name = 'weapon_grenade', label = 'El Bombası', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Bombalandı / Patladı / Patlatıldı / Havaya uçuruldu' },
	[`weapon_bzgas`]                 = { name = 'weapon_bzgas', label = 'BZ Gazı', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_molotov`]               = { name = 'weapon_molotov', label = 'Molotof', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Yakıldı / Alev aldı / Izgara yapıldı' },
	[`weapon_stickybomb`]            = { name = 'weapon_stickybomb', label = 'C4', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Bombalandı / Patladı / Patlatıldı / Havaya uçuruldu' },
	[`weapon_proxmine`]              = { name = 'weapon_proxmine', label = 'Yakınlık Mayını', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Bombalandı / Patladı / Patlatıldı / Havaya uçuruldu' },
	[`weapon_snowball`]              = { name = 'weapon_snowball', label = 'Kartopu', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_pipebomb`]              = { name = 'weapon_pipebomb', label = 'Boru Bombası', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Bombalandı / Patladı / Patlatıldı / Havaya uçuruldu' },
	[`weapon_ball`]                  = { name = 'weapon_ball', label = 'Top', weapontype = 'Fırlatılabilir', ammotype = 'AMMO_BALL', damagereason = 'Öldü' },
	[`weapon_smokegrenade`]          = { name = 'weapon_smokegrenade', label = 'Duman Bombası', weapontype = 'Fırlatılabilir', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_flare`]                 = { name = 'weapon_flare', label = 'İşaret Fişeği', weapontype = 'Fırlatılabilir', ammotype = 'AMMO_FLARE', damagereason = 'Öldü' },

	-- Miscellaneous
	[`weapon_petrolcan`]             = { name = 'weapon_petrolcan', label = 'Benzin Bidonu', weapontype = 'Çeşitli', ammotype = 'AMMO_PETROLCAN', damagereason = 'Öldü' },
	[`gadget_parachute`]             = { name = 'gadget_parachute', label = 'Paraşüt', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_fireextinguisher`]      = { name = 'weapon_fireextinguisher', label = 'Yangın Söndürücü', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_hazardcan`]             = { name = 'weapon_hazardcan', label = 'Tehlikeli Madde Bidonu', weapontype = 'Çeşitli', ammotype = 'AMMO_PETROLCAN', damagereason = 'Öldü' },
	[`weapon_fertilizercan`]         = { name = 'weapon_fertilizercan', label = 'Gübre Bidonu', weapontype = 'Çeşitli', ammotype = 'AMMO_FERTILIZERCAN', damagereason = 'Öldü' },
	[`weapon_barbed_wire`]           = { name = 'weapon_barbed_wire', label = 'Dikenli Tel', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Dikenlere takıldı' },
	[`weapon_drowning`]              = { name = 'weapon_drowning', label = 'Boğulma', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_drowning_in_vehicle`]   = { name = 'weapon_drowning_in_vehicle', label = 'Araçta Boğulma', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_bleeding`]              = { name = 'weapon_bleeding', label = 'Kanama', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Kan kaybından öldü' },
	[`weapon_electric_fence`]        = { name = 'weapon_electric_fence', label = 'Elektrikli Çit', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Elektrik çarptı' },
	[`weapon_explosion`]             = { name = 'weapon_explosion', label = 'Patlama', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldürüldü / Patladı / Yok edildi / Mahvetti / Silindi / Tamamen imha edildi' },
	[`weapon_fall`]                  = { name = 'weapon_fall', label = 'Düşme', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'İntihar etti' },
	[`weapon_exhaustion`]            = { name = 'weapon_exhaustion', label = 'Tükenmişlik', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_hit_by_water_cannon`]   = { name = 'weapon_hit_by_water_cannon', label = 'Su Topu', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Öldü' },
	[`weapon_rammed_by_car`]         = { name = 'weapon_rammed_by_car', label = 'Çarpma - Araç', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Ezip geçti / Ezildi / Çiğnendi' },
	[`weapon_run_over_by_car`]       = { name = 'weapon_run_over_by_car', label = 'Ezilme - Araç', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Ezip geçti / Ezildi / Çiğnendi' },
	[`weapon_heli_crash`]            = { name = 'weapon_heli_crash', label = 'Helikopter Kazası', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Helikopter kazası' },
	[`weapon_fire`]                  = { name = 'weapon_fire', label = 'Yangın', weapontype = 'Çeşitli', ammotype = nil, damagereason = 'Yakıldı / Alev aldı / Izgara yapıldı' },

	-- Animals
	[`weapon_animal`]                = { name = 'weapon_animal', label = 'Hayvan', weapontype = 'Hayvanlar', ammotype = nil, damagereason = 'Parçalandı' },
	[`weapon_cougar`]                = { name = 'weapon_cougar', label = 'Puma', weapontype = 'Hayvanlar', ammotype = nil, damagereason = 'Parçalandı' },
}
