name: testsv Hard RP
version: v1.0.0
author: aosdev
description: testsv-qbcore GitHub deploy — QBCore hard RP (Zap / txAdmin)

tasks:
  - action: download_github
    src: galaktik-yazilim/testsv-qbcore
    ref: main
    dest: ./tmp/repo

  - action: move_path
    src: ./tmp/repo/QBCore_2F0666.base/resources
    dest: ./resources
    overwrite: true

  - action: copy_path
    src: ./tmp/repo/deploy/server.cfg.template
    dest: ./server.cfg

  - action: copy_path
    src: ./tmp/repo/QBCore_2F0666.base/myLogo.png
    dest: ./myLogo.png

  - action: remove_path
    path: ./tmp

  - action: connect_database

  - action: query_database
    file: ./resources/[qb]/qb-core/qbcore.sql
