Config = Config or {}

Config.MinZOffset = 30
Config.RamsNeeded = 2
Config.UnownedBlips = false

Config.Houses = {}
Config.Targets = {}
Config.StashWeights = { -- Please follow by tiers!
	[1] = {
		maxweight = 1000000,
		slots = 50,
	}
}

Config.Furniture = {
	sofas = {
		label = 'Koltuklar',
		items = {
			{ object = 'miss_rub_couch_01',           price = 300,  label = 'Eski kanepe' },
			{ object = 'prop_fib_3b_bench',           price = 700,  label = 'Üç kişilik kanepe' },
			{ object = 'prop_ld_farm_chair01',        price = 250,  label = 'Eski sandalye' },
			{ object = 'prop_ld_farm_couch01',        price = 300,  label = 'Eski üç kişilik kanepe' },
			{ object = 'prop_ld_farm_couch02',        price = 300,  label = 'Eski çizgili kanepe' },
			{ object = 'v_res_d_armchair',            price = 300,  label = 'Eski tek kişilik sarı koltuk' },
			{ object = 'v_res_fh_sofa',               price = 3700, label = 'Köşe kanepe' },
			{ object = 'v_res_mp_sofa',               price = 3700, label = 'Köşe kanepe 2' },
			{ object = 'v_res_d_sofa',                price = 700,  label = 'Kanepe 1' },
			{ object = 'v_res_j_sofa',                price = 700,  label = 'Kanepe 2' },
			{ object = 'v_res_mp_stripchair',         price = 700,  label = 'Kanepe 3' },
			{ object = 'v_res_m_h_sofa_sml',          price = 700,  label = 'Kanepe 4' },
			{ object = 'v_res_r_sofa',                price = 700,  label = 'Kanepe 5' },
			{ object = 'v_res_tre_sofa',              price = 700,  label = 'Kanepe 6' },
			{ object = 'v_res_tre_sofa_mess_a',       price = 700,  label = 'Kanepe 7' },
			{ object = 'v_res_tre_sofa_mess_b',       price = 700,  label = 'Kanepe 8' },
			{ object = 'v_res_tre_sofa_mess_c',       price = 700,  label = 'Kanepe 9' },
			{ object = 'v_res_tt_sofa',               price = 700,  label = 'Kanepe 10' },
			{ object = 'prop_rub_couch02',            price = 700,  label = 'Kanepe 11' },
			{ object = 'v_ilev_m_sofa',               price = 2000, label = 'Beyaz kanepe' },
			{ object = 'v_med_p_sofa',                price = 1000, label = 'Kahverengi deri kanepe' },
			{ object = 'v_club_officesofa',           price = 500,  label = 'Kırmızı basit kanepe' },
			{ object = 'bkr_prop_clubhouse_sofa_01a', price = 1000, label = 'Siyah kanepe' },
			{ object = 'apa_mp_h_stn_sofacorn_01',    price = 5000, label = 'Köşe kanepe 3' },
			{ object = 'prop_couch_lg_02',            price = 1000, label = 'Ahşap kanepe' },
			{ object = 'apa_mp_h_stn_sofacorn_10',    price = 5000, label = 'Köşe kanepe 4' },
			{ object = 'apa_mp_h_yacht_sofa_02',      price = 1000, label = 'Kahverengi kanepe' },
			{ object = 'apa_mp_h_yacht_sofa_01',      price = 5000, label = 'Beyaz uzun kanepe' },
			{ object = 'prop_couch_01',               price = 1000, label = 'Yastıklı kanepe' },
			{ object = 'prop_couch_03',               price = 1000, label = 'Sarı kanepe' },
			{ object = 'prop_couch_04',               price = 1000, label = 'Deri yastıklı kanepe' },
			{ object = 'prop_couch_lg_05',            price = 500,  label = 'Kadife kanepe' },
			{ object = 'prop_couch_lg_06',            price = 1000, label = 'Kahverengi deri kanepe 2' },
			{ object = 'prop_couch_lg_07',            price = 1000, label = 'Yastıklı kanepe 2' },
			{ object = 'prop_couch_lg_08',            price = 1000, label = 'Kahverengi deri kanepe 3' },
			{ object = 'prop_couch_sm1_07',           price = 500,  label = 'Deri köşe kanepe' },
			{ object = 'prop_couch_sm2_07',           price = 500,  label = 'Deri düz kanepe' },
			{ object = 'prop_couch_sm_06',            price = 500,  label = 'Küçük deri kanepe' },
			{ object = 'apa_mp_h_stn_sofa2seat_02',   price = 1000, label = 'İkili koltuk' },
			{ object = 'apa_mp_h_stn_sofacorn_05',    price = 5000, label = 'Köşe kanepe 5' },
			{ object = 'apa_mp_h_stn_sofacorn_06',    price = 5000, label = 'Köşe kanepe 6' },
			{ object = 'apa_mp_h_stn_sofacorn_07',    price = 5000, label = 'Köşe kanepe 7' },
			{ object = 'apa_mp_h_stn_sofacorn_08',    price = 5000, label = 'Köşe kanepe 8' },
			{ object = 'apa_mp_h_stn_sofacorn_09',    price = 5000, label = 'Köşe kanepe 9' },
			{ object = 'ex_mp_h_off_sofa_003',        price = 1000, label = 'Mavi kumaş kanepe' },
			{ object = 'ex_mp_h_off_sofa_01',         price = 1000, label = 'Beyaz deri kanepe' },
			{ object = 'ex_mp_h_off_sofa_02',         price = 1000, label = 'Siyah deri kanepe' },
			{ object = 'hei_heist_stn_sofa2seat_03',  price = 1000, label = 'Modern kanepe' },
			{ object = 'hei_heist_stn_sofa2seat_06',  price = 1000, label = 'Kahverengi kanepe' },
			{ object = 'hei_heist_stn_sofa3seat_01',  price = 1000, label = 'Şezlong' },
			{ object = 'hei_heist_stn_sofa3seat_02',  price = 1000, label = 'Modern kanepe 2' },
			{ object = 'hei_heist_stn_sofa3seat_06',  price = 1000, label = 'Modern kanepe 3' },
			{ object = 'imp_prop_impexp_sofabed_01a', price = 1000, label = 'Kanepe yatak' },
			{ object = 'prop_t_sofa_02',              price = 1000, label = 'Kanepe yatak 2' }
		},
	},
	chairs = {
		label = "Sandalyeler",
		items = {
			{ object = 'v_res_d_highchair',            price = 700,  label = 'Yüksek sandalye' },
			{ object = 'apa_mp_h_stn_chairstrip_03',   price = 500,  label = 'Oturma sandalyesi 4' },
			{ object = 'v_res_fa_chair01',             price = 700,  label = 'Sandalye' },
			{ object = 'v_res_fa_chair02',             price = 700,  label = 'Sandalye 2' },
			{ object = 'v_res_fh_barcchair',           price = 700,  label = 'Yüksek sandalye 2' },
			{ object = 'v_res_fh_dineeamesa',          price = 700,  label = 'Mutfak sandalyesi 1' },
			{ object = 'v_res_fh_dineeamesb',          price = 700,  label = 'Mutfak sandalyesi 2' },
			{ object = 'v_res_fh_dineeamesc',          price = 700,  label = 'Mutfak sandalyesi 3' },
			{ object = 'v_res_fh_easychair',           price = 700,  label = 'Sandalye 3' },
			{ object = 'v_res_fh_kitnstool',           price = 700,  label = 'Sandalye 4' },
			{ object = 'v_res_fh_singleseat',          price = 700,  label = 'Yüksek sandalye 3' },
			{ object = 'v_res_jarmchair',              price = 700,  label = 'Koltuk' },
			{ object = 'v_res_j_dinechair',            price = 700,  label = 'Mutfak sandalyesi 4' },
			{ object = 'v_res_j_stool',                price = 700,  label = 'Sandalye 5' },
			{ object = 'v_res_mbchair',                price = 700,  label = 'MB Sandalye' },
			{ object = 'v_res_m_armchair',             price = 700,  label = 'Koltuk 2' },
			{ object = 'v_res_m_dinechair',            price = 700,  label = 'Mutfak sandalyesi 5' },
			{ object = 'v_res_study_chair',            price = 700,  label = 'Çalışma sandalyesi' },
			{ object = 'v_res_trev_framechair',        price = 700,  label = 'Çerçeveli sandalye' },
			{ object = 'v_res_tre_chair',              price = 700,  label = 'Sandalye 5' },
			{ object = 'v_res_tre_officechair',        price = 700,  label = 'Ofis sandalyesi' },
			{ object = 'v_res_tre_stool',              price = 700,  label = 'Sandalye 6' },
			{ object = 'v_res_tre_stool_leather',      price = 700,  label = 'Deri sandalye' },
			{ object = 'v_res_tre_stool_scuz',         price = 700,  label = 'Eski sandalye' },
			{ object = 'v_med_p_deskchair',            price = 700,  label = 'Masa sandalyesi' },
			{ object = 'v_med_p_easychair',            price = 700,  label = 'Rahat koltuk' },
			{ object = 'v_med_whickerchair1',          price = 700,  label = 'Hasır sandalye' },
			{ object = 'prop_direct_chair_01',         price = 700,  label = 'Yönetmen sandalyesi' },
			{ object = 'prop_direct_chair_02',         price = 700,  label = 'Yönetmen sandalyesi 2' },
			{ object = 'prop_yacht_lounger',           price = 700,  label = 'Yat sandalyesi 1' },
			{ object = 'prop_yacht_seat_01',           price = 700,  label = 'Yat sandalyesi 2' },
			{ object = 'prop_yacht_seat_02',           price = 700,  label = 'Yat sandalyesi 3' },
			{ object = 'prop_yacht_seat_03',           price = 700,  label = 'Yat sandalyesi 4' },
			{ object = 'v_ret_chair_white',            price = 100,  label = 'Beyaz sandalye' },
			{ object = 'v_ret_chair',                  price = 100,  label = 'Sandalye 7' },
			{ object = 'v_ret_ta_stool',               price = 100,  label = 'TA Sandalye' },
			{ object = 'prop_cs_office_chair',         price = 100,  label = 'Ofis sandalyesi 2' },
			{ object = 'apa_mp_h_yacht_armchair_01',   price = 1000, label = 'Beyaz berjer' },
			{ object = 'v_club_barchair',              price = 300,  label = 'Sandalye 8' },
			{ object = 'prop_off_chair_04',            price = 300,  label = 'Masa sandalyesi 2' },
			{ object = 'v_club_stagechair',            price = 500,  label = 'Pembe berjer' },
			{ object = 'v_club_officechair',           price = 500,  label = 'Masa sandalyesi 3' },
			{ object = 'prop_armchair_01',             price = 500,  label = 'Oturma sandalyesi' },
			{ object = 'prop_bar_stool_01',            price = 300,  label = 'Bar taburesi' },
			{ object = 'apa_mp_h_yacht_stool_01',      price = 300,  label = 'Beyaz puf' },
			{ object = 'apa_mp_h_stn_chairarm_12',     price = 500,  label = 'Oturma sandalyesi 3' },
			{ object = 'apa_mp_h_stn_chairstool_12',   price = 300,  label = 'Ayak desteği' },
			{ object = 'prop_chair_03',                price = 100,  label = 'Ahşap sandalye' },
			{ object = 'prop_couch_sm_05',             price = 500,  label = 'Kadife koltuk' },
			{ object = 'prop_couch_sm_07',             price = 300,  label = 'Beyaz koltuk 2' },
			{ object = 'prop_couch_sm_02',             price = 300,  label = 'Turuncu koltuk' },
			{ object = 'apa_mp_h_stn_sofa_daybed_01',  price = 500,  label = 'Salon koltuğu' },
			{ object = 'apa_mp_h_stn_sofa_daybed_02',  price = 500,  label = 'Salon koltuğu 2' },
			{ object = 'apa_mp_h_din_chair_04',        price = 500,  label = 'Modern sandalye' },
			{ object = 'apa_mp_h_din_chair_08',        price = 500,  label = 'Modern sandalye 2' },
			{ object = 'apa_mp_h_din_chair_09',        price = 500,  label = 'Modern sandalye 3' },
			{ object = 'apa_mp_h_din_chair_12',        price = 500,  label = 'Modern sandalye 4' },
			{ object = 'apa_mp_h_din_stool_04',        price = 500,  label = 'Modern sandalye 5' },
			{ object = 'apa_mp_h_stn_chairarm_01',     price = 500,  label = 'Modern sandalye 6' },
			{ object = 'apa_mp_h_stn_chairarm_02',     price = 500,  label = 'Modern sandalye 7' },
			{ object = 'apa_mp_h_stn_chairarm_03',     price = 500,  label = 'Modern sandalye 8' },
			{ object = 'apa_mp_h_stn_chairarm_09',     price = 500,  label = 'Modern sandalye 9' },
			{ object = 'apa_mp_h_stn_chairarm_11',     price = 500,  label = 'Modern sandalye 10' },
			{ object = 'apa_mp_h_stn_chairarm_13',     price = 500,  label = 'Modern sandalye 11' },
			{ object = 'apa_mp_h_stn_chairarm_24',     price = 500,  label = 'Modern sandalye 12' },
			{ object = 'apa_mp_h_stn_chairarm_25',     price = 500,  label = 'Modern sandalye 13' },
			{ object = 'apa_mp_h_stn_chairarm_26',     price = 500,  label = 'Modern sandalye 14' },
			{ object = 'apa_mp_h_stn_chairstrip_04',   price = 500,  label = 'Modern sandalye 15' },
			{ object = 'apa_mp_h_stn_chairstrip_05',   price = 500,  label = 'Modern sandalye 16' },
			{ object = 'apa_mp_h_stn_chairstrip_08',   price = 500,  label = 'Modern sandalye 17' },
			{ object = 'apa_mp_h_stn_foot_stool_01',   price = 500,  label = 'Puf' },
			{ object = 'apa_mp_h_stn_foot_stool_02',   price = 500,  label = 'Puf 2' },
			{ object = 'apa_mp_h_yacht_barstool_01',   price = 500,  label = 'Bar taburesi 2' },
			{ object = 'ba_prop_int_glam_stool',       price = 500,  label = 'Bar taburesi 3' },
			{ object = 'ba_prop_battle_club_chair_01', price = 500,  label = 'Ofis sandalyesi' },
			{ object = 'ba_prop_battle_club_chair_02', price = 500,  label = 'Ofis sandalyesi 2' },
			{ object = 'ba_prop_battle_club_chair_03', price = 500,  label = 'Ofis sandalyesi 3' },
			{ object = 'ba_prop_battle_control_seat',  price = 500,  label = 'Oyuncu sandalyesi' }
		},
	},
	beds = {
		label = 'Yataklar',
		items = {
			{ object = 'v_res_d_bed',                price = 700,  label = 'Yatak 1' },
			{ object = 'v_res_lestersbed',           price = 700,  label = 'Yatak 2' },
			{ object = 'v_res_mbbed',                price = 700,  label = 'MB Yatak' },
			{ object = 'v_res_mdbed',                price = 700,  label = 'MD Yatak' },
			{ object = 'v_res_msonbed',              price = 700,  label = 'Yatak 3' },
			{ object = 'v_res_tre_bed1',             price = 700,  label = 'Yatak 4' },
			{ object = 'v_res_tre_bed2',             price = 700,  label = 'T Yatak' },
			{ object = 'v_res_tt_bed',               price = 700,  label = 'TT Yatak' },
			{ object = 'apa_mp_h_bed_with_table_02', price = 5000, label = 'Lüks yatak' },
			{ object = 'apa_mp_h_bed_wide_05',       price = 5000, label = 'Kırmızı yatak' },
			{ object = 'apa_mp_h_bed_double_08',     price = 3000, label = 'Kare yatak' },
			{ object = 'apa_mp_h_bed_double_09',     price = 3000, label = 'Modern yatak' },
			{ object = 'apa_mp_h_yacht_bed_01',      price = 5000, label = 'California King yatak' },
			{ object = 'apa_mp_h_yacht_bed_02',      price = 5000, label = 'California King yatak 2' },
			{ object = 'bkr_prop_biker_campbed_01',  price = 100,  label = 'Kamp yatağı' },
			{ object = 'ex_prop_exec_bed_01',        price = 700,  label = 'Küçük yatak' },
			{ object = 'gr_prop_bunker_bed_01',      price = 700,  label = 'Küçük yatak 2' },
			{ object = 'p_mbbed_s',                  price = 700,  label = 'Yatak 5' }
		},
	},
	general = {
		label = 'Genel',
		items = {
			{ object = 'v_corp_facebeanbag',       price = 100,  label = 'Fasulye torbası 1' },
			{ object = 'v_res_cherubvase',         price = 2500, label = 'Beyaz vazo' },
			{ object = 'v_res_d_paddedwall',       price = 300,  label = 'Döşemeli duvar' },
			{ object = 'v_res_d_ramskull',         price = 300,  label = 'Eşya' },
			{ object = 'v_res_d_whips',            price = 300,  label = 'Kırbaçlar' },
			{ object = 'v_res_fashmag1',           price = 300,  label = 'Dergiler' },
			{ object = 'v_res_fashmagopen',        price = 300,  label = 'Açık dergiler' },
			{ object = 'v_res_fa_magtidy',         price = 300,  label = 'Dergi düzenleyici' },
			{ object = 'v_res_fa_yogamat002',      price = 300,  label = 'Yoga matı 1' },
			{ object = 'v_res_fa_yogamat1',        price = 300,  label = 'Yoga matı 2' },
			{ object = 'v_res_fh_aftershavebox',   price = 300,  label = 'Traş losyonu' },
			{ object = 'v_res_fh_flowersa',        price = 300,  label = 'Çiçekler' },
			{ object = 'v_res_fh_fruitbowl',       price = 300,  label = 'Meyve kasesi' },
			{ object = 'v_res_fh_laundrybasket',   price = 300,  label = 'Çamaşır sepeti' },
			{ object = 'v_res_fh_pouf',            price = 300,  label = 'Puf' },
			{ object = 'v_res_fh_sculptmod',       price = 300,  label = 'Heykel' },
			{ object = 'v_res_j_magrack',          price = 300,  label = 'Dergi rafı' },
			{ object = 'v_res_jewelbox',           price = 300,  label = 'Mücevher kutusu' },
			{ object = 'v_res_mbbin',              price = 300,  label = 'Çöp kutusu' },
			{ object = 'v_res_mbowlornate',        price = 300,  label = 'Süslü kase' },
			{ object = 'v_res_mbronzvase',         price = 300,  label = 'Bronz vazo' },
			{ object = 'v_res_mchalkbrd',          price = 300,  label = 'Tebeşir tahtası' },
			{ object = 'v_res_mddresser',          price = 300,  label = 'Şifonyer' },
			{ object = 'v_res_mplinth',            price = 300,  label = 'Kaide' },
			{ object = 'v_res_mp_ashtrayb',        price = 300,  label = 'Kül tablası' },
			{ object = 'v_res_m_candle',           price = 300,  label = 'Mum' },
			{ object = 'v_res_m_candlelrg',        price = 300,  label = 'Büyük mum' },
			{ object = 'v_res_m_kscales',          price = 300,  label = 'Terazi' },
			{ object = 'v_res_tt_bedpillow',       price = 300,  label = 'Yastık' },
			{ object = 'v_med_cor_whiteboard',     price = 300,  label = 'Beyaz tahta' },
			{ object = 'prop_ashtray_01',          price = 100,  label = 'Siyah kül tablası' },
			{ object = 'v_ret_fh_ashtray',         price = 100,  label = 'Taş kül tablası' },
			{ object = 'v_24_wdr_mesh_rugs',       price = 500,  label = 'Halı' },
			{ object = 'apa_mp_h_acc_rugwooll_04', price = 500,  label = 'Halı 2' },
			{ object = 'ex_mp_h_acc_rugwoolm_04',  price = 500,  label = 'Halı 3' },
			{ object = 'apa_mp_h_acc_rugwoolm_03', price = 500,  label = 'Halı 4' },
			{ object = 'apa_mp_h_acc_rugwooll_03', price = 500,  label = 'Halı 5' },
			{ object = 'apa_mp_h_acc_rugwoolm_04', price = 500,  label = 'Halı 6' },
			{ object = 'v_club_rack',              price = 500,  label = 'Elbise askısı' }
		},
	},
	general2 = {
		label = 'Aksesuarlar',
		items = {
			{ object = 'prop_a4_pile_01',               price = 100, label = 'A4 kağıt yığını' },
			{ object = 'prop_amb_40oz_03',              price = 100, label = '40 oz' },
			{ object = 'prop_amb_beer_bottle',          price = 100, label = 'Bira' },
			{ object = 'prop_aviators_01',              price = 100, label = 'Aviator gözlük' },
			{ object = 'prop_barry_table_detail',       price = 100, label = 'Detay' },
			{ object = 'prop_beer_box_01',              price = 100, label = 'Biralar' },
			{ object = 'prop_binoc_01',                 price = 100, label = 'Dürbün' },
			{ object = 'prop_blox_spray',               price = 100, label = 'Blox sprey' },
			{ object = 'prop_bongos_01',                price = 100, label = 'Bongo' },
			{ object = 'prop_bong_01',                  price = 100, label = 'Nargile' },
			{ object = 'prop_boombox_01',               price = 100, label = 'Boombox' },
			{ object = 'prop_bowl_crisps',              price = 100, label = 'Cips kasesi' },
			{ object = 'prop_candy_pqs',                price = 100, label = 'Şeker' },
			{ object = 'prop_carrier_bag_01',           price = 100, label = 'Taşıma çantası' },
			{ object = 'prop_ceramic_jug_01',           price = 100, label = 'Seramik sürahi' },
			{ object = 'prop_cigar_pack_01',            price = 100, label = 'Puro paketi 1' },
			{ object = 'prop_cigar_pack_02',            price = 100, label = 'Puro paketi 2' },
			{ object = 'prop_cs_beer_box',              price = 100, label = 'Bira kutusu 2' },
			{ object = 'prop_cs_binder_01',             price = 100, label = 'Dosya' },
			{ object = 'prop_cs_bs_cup',                price = 100, label = 'Bardak' },
			{ object = 'prop_cs_cashenvelope',          price = 100, label = 'Zarf' },
			{ object = 'prop_cs_champ_flute',           price = 100, label = 'Flüt kadehi' },
			{ object = 'prop_cs_duffel_01',             price = 100, label = 'Spor çantası' },
			{ object = 'prop_cs_dvd',                   price = 50,  label = 'DVD' },
			{ object = 'prop_cs_dvd_case',              price = 50,  label = 'DVD kutusu' },
			{ object = 'prop_cs_film_reel_01',          price = 100, label = 'Film makarası' },
			{ object = 'prop_cs_ilev_blind_01',         price = 100, label = 'Stor perde' },
			{ object = 'p_ld_bs_bag_01',                price = 100, label = 'Çanta' },
			{ object = 'prop_cs_ironing_board',         price = 100, label = 'Ütü masası' },
			{ object = 'prop_cs_katana_01',             price = 100, label = 'Katana' },
			{ object = 'prop_cs_kettle_01',             price = 100, label = 'Su ısıtıcısı' },
			{ object = 'prop_cs_lester_crate',          price = 100, label = 'Kasa' },
			{ object = 'prop_cs_petrol_can',            price = 100, label = 'Benzin bidonu' },
			{ object = 'prop_cs_sack_01',               price = 100, label = 'Torba' },
			{ object = 'prop_cs_script_bottle_01',      price = 100, label = 'Reçete şişesi' },
			{ object = 'prop_cs_script_bottle',         price = 100, label = 'Reçete şişesi 2' },
			{ object = 'prop_cs_street_binbag_01',      price = 100, label = 'Çöp torbası' },
			{ object = 'prop_cs_whiskey_bottle',        price = 100, label = 'Viski şişesi' },
			{ object = 'prop_sh_bong_01',               price = 100, label = 'Nargile' },
			{ object = 'prop_peanut_bowl_01',           price = 100, label = 'Fıstık' },
			{ object = 'prop_tumbler_01',               price = 100, label = 'Kadeh' },
			{ object = 'prop_weed_bottle',              price = 100, label = 'Ot tüpü' },
			{ object = 'p_cs_lighter_01',               price = 100, label = 'Çakmak' },
			{ object = 'p_cs_papers_01',                price = 100, label = 'Sarma kağıdı' },
			{ object = 'v_res_d_dildo_f',               price = 100, label = 'Siyah dildo' },
			{ object = 'v_res_d_dildo_c',               price = 100, label = 'Beyaz dildo' },
			{ object = 'v_res_d_dildo_a',               price = 100, label = "Anne oyuncağı" },
			{ object = 'prop_champ_cool',               price = 100, label = 'Şampanya soğutucusu' },
			{ object = 'prop_champ_01b',                price = 100, label = 'Şampanya şişesi' },
			{ object = 'prop_champ_flute',              price = 100, label = 'Şampanya kadehi' },
			{ object = 'ba_prop_club_champset',         price = 300, label = 'Şampanya seti' },
			{ object = 'v_res_fa_candle01',             price = 100, label = 'Mavi mum' },
			{ object = 'v_res_fa_candle02',             price = 100, label = 'Kırmızı mum' },
			{ object = 'v_res_fa_candle03',             price = 100, label = 'Siyah mum' },
			{ object = 'v_res_fa_candle04',             price = 100, label = 'Küçük mum' },
			{ object = 'v_med_bottles2',                price = 100, label = 'Kimyasallar' },
			{ object = 'v_res_desktidy',                price = 100, label = 'Ofis malzemeleri' },
			{ object = 'v_med_p_notebook',              price = 100, label = "Notlar" },
			{ object = 'bkr_prop_weed_dry_01a',         price = 100, label = 'Ot yığını' },
			{ object = 'ba_prop_battle_trophy_battler', price = 100, label = 'Yumruk kupası' },
			{ object = 'ba_prop_battle_trophy_no1',     price = 100, label = 'Yıldız kupası' },
			{ object = 'prop_golf_bag_01c',             price = 100, label = 'Golf çantası' },
			{ object = 'hei_heist_kit_bin_01',          price = 100, label = 'Çöp kutusu' },
			{ object = 'prop_wooden_barrel',            price = 100, label = 'Ahşap fıçı' },
			{ object = 'bkr_prop_bkr_cash_scatter_01',  price = 100, label = 'Dağılmış para' },
			{ object = 'bkr_prop_bkr_cashpile_01',      price = 100, label = 'Nakit' },
			{ object = 'bkr_prop_bkr_cash_roll_01',     price = 100, label = 'Nakit rulosu' },
			{ object = 'bkr_prop_bkr_cashpile_04',      price = 100, label = 'Nakit yığını' },
			{ object = 'bkr_prop_weed_bigbag_open_01a', price = 100, label = 'Açık ot torbası' },
			{ object = 'bkr_prop_weed_bigbag_02a',      price = 100, label = 'Ot torbası 2' },
			{ object = 'bkr_prop_weed_bigbag_03a',      price = 100, label = 'Ot torbası 3' },
			{ object = 'bkr_prop_weed_scales_01a',      price = 100, label = 'Terazi' },
			{ object = 'bkr_prop_weed_smallbag_01a',    price = 100, label = 'Küçük torba' },
			{ object = 'prop_gold_bar',                 price = 100, label = 'Altın külçe' },
			{ object = 'beerrow_world',                 price = 100, label = 'Bira şişeleri' },
			{ object = 'beerrow_local',                 price = 100, label = 'Bira şişeleri 2' },
			{ object = 'p_cs_bbbat_01',                 price = 100, label = 'Sopa' },
			{ object = 'p_cs_cuffs_02_s',               price = 100, label = 'Kelepçe' },
			{ object = 'p_cs_joint_02',                 price = 100, label = 'Joint' },
			{ object = 'p_ing_coffeecup_01',            price = 100, label = 'Kahve fincanı' },
			{ object = 'p_tumbler_cs2_s',               price = 100, label = 'Kadeh' },
			{ object = 'prop_turkey_leg_01',            price = 100, label = 'Tavuk budu' },
			{ object = 'prop_amb_donut',                price = 100, label = 'Donut' },
			{ object = 'prop_donut_02',                 price = 100, label = 'Donut 2' },
			{ object = 'prop_bar_shots',                price = 100, label = 'Bar shotları' },
			{ object = 'prop_bar_stirrers',             price = 100, label = 'Bar karıştırıcıları' },
			{ object = 'prop_beer_amopen',              price = 100, label = 'Açık bira' },
			{ object = 'prop_beer_blr',                 price = 100, label = 'Bira 1' },
			{ object = 'prop_beer_logger',              price = 100, label = 'Bira 2' },
			{ object = 'prop_beer_stzopen',             price = 100, label = 'Bira 3' },
			{ object = 'prop_bikerset',                 price = 100, label = 'Biker seti' },
			{ object = 'prop_bottle_brandy',            price = 100, label = 'Konyak şişesi' },
			{ object = 'prop_tequila_bottle',           price = 100, label = 'Tekila şişesi' },
			{ object = 'prop_tequila',                  price = 100, label = 'Tekila' },
			{ object = 'prop_bottle_cognac',            price = 100, label = 'Konyak şişesi' },
			{ object = 'prop_bottle_macbeth',           price = 100, label = 'Macbeth şişesi' },
			{ object = 'prop_brandy_glass',             price = 100, label = 'Konyak bardağı' },
			{ object = 'prop_mug_01',                   price = 100, label = 'Kupa 1' },
			{ object = 'prop_mug_02',                   price = 100, label = 'Kupa 2' },
			{ object = 'prop_mug_03',                   price = 100, label = 'Kupa 3' },
			{ object = 'prop_optic_vodka',              price = 100, label = 'Votka' },
			{ object = 'prop_optic_jd',                 price = 100, label = 'JD' },
			{ object = 'prop_pint_glass_01',            price = 100, label = 'Pint bardağı' },
			{ object = 'prop_pizza_box_03',             price = 100, label = 'Pizza kutusu' },
			{ object = 'prop_sandwich_01',              price = 100, label = 'Sandviç' },
			{ object = 'prop_cava',                     price = 100, label = 'Cava' },
			{ object = 'prop_drink_redwine',            price = 100, label = 'Kırmızı şarap' },
			{ object = 'vodkarow',                      price = 100, label = 'Votka sırası' },
			{ object = 'prop_cherenkov_02',             price = 100, label = 'Cherenkov' },
			{ object = 'prop_cherenkov_03',             price = 100, label = 'Cherenkov 2' },
			{ object = 'prop_cocktail_glass',           price = 100, label = 'Kokteyl bardağı' },
			{ object = 'prop_cs_bottle_opener',         price = 100, label = 'Şişe açacağı' },
			{ object = 'prop_food_bs_chips',            price = 100, label = 'Cips' },
			{ object = 'prop_cs_burger_01',             price = 100, label = 'Burger' },
			{ object = 'prop_cs_hand_radio',            price = 100, label = 'El telsizi' },
			{ object = 'prop_cs_hotdog_01',             price = 100, label = 'Hotdog' },
			{ object = 'prop_cs_milk_01',               price = 100, label = 'Süt' },
			{ object = 'prop_cs_panties',               price = 100, label = 'Külot' },
			{ object = 'prop_cs_steak',                 price = 100, label = 'Et' }
		},
	},
	general3 = {
		label = 'Çeşitli',
		items = {
			{ object = 'v_ret_csr_bin',            price = 100,  label = 'CSR çöp kutusu' },
			{ object = 'v_ret_fh_wickbskt',        price = 100,  label = 'Sepet' },
			{ object = 'v_ret_gc_bag01',           price = 100,  label = 'GC çanta 1' },
			{ object = 'v_ret_gc_bag02',           price = 100,  label = 'GC çanta 2' },
			{ object = 'v_ret_gc_bin',             price = 100,  label = 'GC çöp kutusu' },
			{ object = 'v_ret_gc_cashreg',         price = 100,  label = 'Yazar kasa' },
			{ object = 'v_ret_gc_chair01',         price = 100,  label = 'GC sandalye 01' },
			{ object = 'v_ret_gc_chair02',         price = 100,  label = 'GC sandalye 02' },
			{ object = 'v_ret_gc_clock',           price = 100,  label = 'Saat' },
			{ object = 'v_ret_hd_prod1_',          price = 100,  label = 'Ürün 1' },
			{ object = 'v_ret_hd_prod2_',          price = 100,  label = 'Ürün 2' },
			{ object = 'v_ret_hd_prod3_',          price = 100,  label = 'Ürün 3' },
			{ object = 'v_ret_hd_prod4_',          price = 100,  label = 'Ürün 4' },
			{ object = 'v_ret_hd_prod5_',          price = 100,  label = 'Ürün 5' },
			{ object = 'v_ret_hd_prod6_',          price = 100,  label = 'Ürün 6' },
			{ object = 'v_ret_hd_unit1_',          price = 100,  label = 'HD ünite 1' },
			{ object = 'v_ret_hd_unit2_',          price = 100,  label = 'HD ünite 2' },
			{ object = 'v_ret_ml_fridge02',        price = 100,  label = 'Buzdolabı' },
			{ object = 'v_ret_ps_bag_01',          price = 100,  label = 'Çanta 1' },
			{ object = 'v_ret_ps_bag_02',          price = 100,  label = 'Çanta 2' },
			{ object = 'v_ret_ta_book1',           price = 100,  label = 'Kitap 1' },
			{ object = 'v_ret_ta_book2',           price = 100,  label = 'Kitap 2' },
			{ object = 'v_ret_ta_book3',           price = 100,  label = 'Kitap 3' },
			{ object = 'v_ret_ta_book4',           price = 100,  label = 'Kitap 4' },
			{ object = 'v_ret_ta_camera',          price = 100,  label = 'Kamera' },
			{ object = 'v_ret_ta_firstaid',        price = 100,  label = 'İlk yardım' },
			{ object = 'v_ret_ta_hero',            price = 100,  label = 'Kahraman' },
			{ object = 'v_ret_ta_mag1',            price = 100,  label = 'Dergi 1' },
			{ object = 'v_ret_ta_mag2',            price = 100,  label = 'Dergi 2' },
			{ object = 'v_ret_ta_skull',           price = 100,  label = 'Kafatası' },
			{ object = 'prop_acc_guitar_01',       price = 100,  label = 'Gitar' },
			{ object = 'prop_amb_handbag_01',      price = 100,  label = 'El çantası' },
			{ object = 'prop_attache_case_01',     price = 100,  label = 'Kasa' },
			{ object = 'prop_big_bag_01',          price = 100,  label = 'Büyük çanta' },
			{ object = 'prop_bonesaw',             price = 100,  label = 'Kemik testeresi' },
			{ object = 'prop_cs_fertilizer',       price = 100,  label = 'Gübre' },
			{ object = 'prop_cs_shopping_bag',     price = 100,  label = 'Alışveriş çantası' },
			{ object = 'prop_cs_vial_01',          price = 100,  label = 'Flakon' },
			{ object = 'prop_defilied_ragdoll_01', price = 100,  label = 'Bebek' },
			{ object = 'v_res_fa_book03',          price = 100,  label = 'Kamasutra kitabı' },
			{ object = 'prop_weight_rack_02',      price = 500,  label = 'Dambıl rafı' },
			{ object = 'prop_weight_bench_02',     price = 500,  label = 'Bench press seti' },
			{ object = 'prop_tool_broom',          price = 100,  label = 'Süpürge' },
			{ object = 'prop_fire_exting_2a',      price = 100,  label = 'Yangın söndürücü' },
			{ object = 'v_res_vacuum',             price = 100,  label = 'Elektrikli süpürge' },
			{ object = 'v_ret_gc_fan',             price = 100,  label = 'Vantilatör' },
			{ object = 'prop_paint_stepl01b',      price = 100,  label = 'Merdiven' },
			{ object = 'bkr_prop_weed_bucket_01b', price = 100,  label = 'Gübre' },
			{ object = 'v_club_vusnaketank',       price = 500,  label = 'Teraryum' },
			{ object = 'prop_pooltable_02',        price = 1500, label = 'Bilardo masası' },
			{ object = 'prop_pool_rack_02',        price = 100,  label = 'Bilardo ıstakaları' },
			{ object = 'v_club_vu_deckcase',       price = 1000, label = 'DJ seti' },
			{ object = 'v_corp_servercln',         price = 1000, label = 'Sunucu rafı' }
		},
	},
	general4 = {
		label = 'Çeşitli 2',
		items = {
			{ object = 'prop_dummy_01',             price = 100, label = 'Manken' },
			{ object = 'prop_egg_clock_01',         price = 100, label = 'Yumurta saati' },
			{ object = 'prop_el_guitar_01',         price = 100, label = 'Elektro gitar 1' },
			{ object = 'prop_el_guitar_02',         price = 100, label = 'Elektro gitar 2' },
			{ object = 'prop_el_guitar_03',         price = 100, label = 'Elektro gitar 2' },
			{ object = 'prop_feed_sack_01',         price = 100, label = 'Yem torbası' },
			{ object = 'prop_floor_duster_01',      price = 100, label = 'Yer paspası' },
			{ object = 'prop_fruit_basket',         price = 100, label = 'Meyve sepeti' },
			{ object = 'prop_f_duster_02',          price = 100, label = 'Toz bezi' },
			{ object = 'prop_grapes_02',            price = 100, label = 'Üzüm' },
			{ object = 'prop_hotel_clock_01',       price = 100, label = 'Otel saati' },
			{ object = 'prop_idol_case_01',         price = 100, label = 'Heykel kutusu' },
			{ object = 'prop_jewel_02a',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_02b',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_02c',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_03a',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_03b',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_04a',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_jewel_04b',            price = 100, label = 'Mücevherler' },
			{ object = 'prop_j_disptray_01',        price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_01b',       price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_02',        price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_03',        price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_04',        price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_04b',       price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_05',        price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_j_disptray_05b',       price = 100, label = 'Teşhir tepsisi' },
			{ object = 'prop_ld_greenscreen_01',    price = 100, label = 'Yeşil perde' },
			{ object = 'prop_ld_handbag',           price = 100, label = 'El çantası' },
			{ object = 'prop_ld_jerrycan_01',       price = 100, label = 'Benzin bidonu' },
			{ object = 'prop_ld_keypad_01',         price = 100, label = 'Tuş takımı 1' },
			{ object = 'prop_ld_keypad_01b',        price = 100, label = 'Tuş takımı 2' },
			{ object = 'prop_ld_suitcase_01',       price = 100, label = 'Bavul 1' },
			{ object = 'prop_ld_suitcase_02',       price = 100, label = 'Bavul 2' },
			{ object = 'hei_p_attache_case_shut',   price = 100, label = 'Bavul 3' },
			{ object = 'prop_mr_rasberryclean',     price = 100, label = 'Rasberry Clean' },
			{ object = 'prop_paper_bag_01',         price = 100, label = 'Kağıt torba' },
			{ object = 'prop_shopping_bags01',      price = 100, label = 'Alışveriş çantaları' },
			{ object = 'prop_shopping_bags02',      price = 100, label = 'Alışveriş çantaları 2' },
			{ object = 'prop_yoga_mat_01',          price = 100, label = 'Yoga matı 1' },
			{ object = 'prop_yoga_mat_02',          price = 100, label = 'Yoga matı 2' },
			{ object = 'prop_yoga_mat_03',          price = 100, label = 'Yoga matı 3' },
			{ object = 'p_ld_sax',                  price = 100, label = 'Saksafon' },
			{ object = 'p_ld_soc_ball_01',          price = 100, label = 'Futbol topu' },
			{ object = 'p_watch_01',                price = 100, label = 'Saat 1' },
			{ object = 'p_watch_02',                price = 100, label = 'Saat 2' },
			{ object = 'p_watch_03',                price = 100, label = 'Saat 3' },
			{ object = 'p_watch_04',                price = 100, label = 'Saat 4' },
			{ object = 'p_watch_05',                price = 100, label = 'Saat 5' },
			{ object = 'p_watch_06',                price = 100, label = 'Saat 6' },
			{ object = 'apa_mp_h_acc_candles_01',   price = 100, label = 'Mum' },
			{ object = 'apa_mp_h_acc_candles_02',   price = 100, label = 'Mum 2' },
			{ object = 'apa_mp_h_acc_candles_04',   price = 100, label = 'Mum 3' },
			{ object = 'apa_mp_h_acc_candles_06',   price = 100, label = 'Mum 4' },
			{ object = 'apa_mp_h_acc_fruitbowl_02', price = 100, label = 'Meyve kasesi' },
			{ object = 'apa_mp_h_acc_tray_01',      price = 100, label = 'Küçük eşyalar' },
			{ object = 'prop_bskball_01',           price = 100, label = 'Basketbol topu' },
			{ object = 'prop_cs_wrench',            price = 100, label = 'Anahtar' },
			{ object = 'prop_cs_bowie_knife',       price = 100, label = 'Bowie bıçağı' },
			{ object = 'prop_w_me_hatchet',         price = 100, label = 'Balta' }
		},
	},
	small = {
		label = 'Detaylar',
		items = {
			{ object = 'v_res_r_figcat',               price = 300, label = 'Kedi figürü' },
			{ object = 'v_res_r_figclown',             price = 300, label = 'Palyaço figürü' },
			{ object = 'v_res_r_figauth2',             price = 300, label = 'Figür' },
			{ object = 'v_res_r_figfemale',            price = 300, label = 'Kadın figürü' },
			{ object = 'v_res_r_figflamenco',          price = 300, label = 'Flamenko figürü' },
			{ object = 'v_res_r_figgirl',              price = 300, label = 'Kız figürü' },
			{ object = 'v_res_r_figgirlclown',         price = 300, label = 'Palyaço kız figürü' },
			{ object = 'v_res_r_figoblisk',            price = 300, label = 'Obelisk figürü' },
			{ object = 'v_res_r_figpillar',            price = 300, label = 'Sütun figürü' },
			{ object = 'v_res_r_teapot',               price = 300, label = 'Demlik' },
			{ object = 'v_res_sculpt_dec',             price = 300, label = 'Heykel 1' },
			{ object = 'v_res_sculpt_decd',            price = 300, label = 'Heykel 2' },
			{ object = 'v_res_sculpt_dece',            price = 300, label = 'Heykel 3' },
			{ object = 'v_res_sculpt_decf',            price = 300, label = 'Heykel 4' },
			{ object = 'v_res_skateboard',             price = 300, label = 'Kaykay' },
			{ object = 'v_res_sketchpad',              price = 300, label = 'Eskiz defteri' },
			{ object = 'v_res_tissues',                price = 300, label = 'Mendiller' },
			{ object = 'v_res_tre_basketmess',         price = 300, label = 'Sepet' },
			{ object = 'v_res_tre_bin',                price = 300, label = 'Çöp kutusu' },
			{ object = 'v_res_tre_cushiona',           price = 300, label = 'Yastık 1' },
			{ object = 'v_res_tre_cushionb',           price = 300, label = 'Yastık 2' },
			{ object = 'v_res_tre_cushionc',           price = 300, label = 'Yastık 3' },
			{ object = 'v_res_tre_cushiond',           price = 300, label = 'Yastık 4' },
			{ object = 'v_res_tre_cushnscuzb',         price = 300, label = 'Yastık 5' },
			{ object = 'v_res_tre_cushnscuzd',         price = 300, label = 'Yastık 6' },
			{ object = 'v_res_tre_fruitbowl',          price = 300, label = 'Meyve kasesi' },
			{ object = 'v_med_p_sideboard',            price = 300, label = 'Konsol' },
			{ object = 'prop_idol_01',                 price = 100, label = 'Heykel 1' },
			{ object = 'v_res_r_fighorsestnd',         price = 300, label = 'Siyah at figürü' },
			{ object = 'v_res_r_fighorse',             price = 300, label = 'Büyük at figürü' },
			{ object = 'v_res_r_figdancer',            price = 300, label = 'Dansçı figürü' },
			{ object = 'v_res_fa_idol02',              price = 300, label = 'Fil figürü' },
			{ object = 'v_res_m_statue',               price = 300, label = 'Heykel' },
			{ object = 'v_20_ornaeagle',               price = 300, label = 'Kartal figürü' },
			{ object = 'v_med_p_vaseround',            price = 300, label = 'Yuvarlak vazo' },
			{ object = 'ex_mp_h_acc_vase_05',          price = 300, label = 'Mor vazo' },
			{ object = 'apa_mp_h_acc_dec_head_01',     price = 300, label = 'Sanat eseri' },
			{ object = 'apa_mp_h_acc_dec_sculpt_02',   price = 300, label = 'Sanat eseri 2' },
			{ object = 'ex_mp_h_acc_dec_plate_02',     price = 300, label = 'Sanat eseri 3' },
			{ object = 'apa_mp_h_acc_bowl_ceramic_01', price = 300, label = 'Kase' },
			{ object = 'apa_mp_h_acc_dec_plate_01',    price = 300, label = 'Terazi 2' },
			{ object = 'apa_mp_h_acc_vase_01',         price = 300, label = 'Siyah beyaz vazo' },
			{ object = 'apa_mp_h_acc_vase_02',         price = 300, label = 'Kırmızı vazo' },
			{ object = 'apa_mp_h_acc_vase_05',         price = 300, label = 'Vazo' },
			{ object = 'apa_mp_h_acc_vase_06',         price = 300, label = 'Siyah beyaz vazo 2' }
		},
	},
	storage = {
		label = 'Depolama',
		items = {
			{ object = 'v_res_cabinet',                   price = 2500, label = 'Büyük dolap' },
			{ object = 'v_res_d_dressingtable',           price = 2500, label = 'Makyaj masası' },
			{ object = 'v_res_d_sideunit',                price = 2500, label = 'Yan ünite' },
			{ object = 'v_res_fh_sidebrddine',            price = 2500, label = 'Yan ünite' },
			{ object = 'v_res_fh_sidebrdlngb',            price = 2500, label = 'Yan ünite' },
			{ object = 'v_res_mbbedtable',                price = 2500, label = 'Yatak ünitesi' },
			{ object = 'v_res_j_tvstand',                 price = 2500, label = 'TV ünitesi' },
			{ object = 'v_res_mbdresser',                 price = 2500, label = 'Şifonyer ünitesi' },
			{ object = 'v_res_mbottoman',                 price = 2500, label = 'Puf ünitesi' },
			{ object = 'v_res_mconsolemod',               price = 2500, label = 'Konsol ünitesi' },
			{ object = 'v_res_mcupboard',                 price = 2500, label = 'Dolap ünitesi' },
			{ object = 'v_res_mdchest',                   price = 2500, label = 'Sandık ünitesi' },
			{ object = 'v_res_msoncabinet',               price = 2500, label = 'Mason ünitesi' },
			{ object = 'v_res_m_armoire',                 price = 2500, label = 'Gardrop ünitesi' },
			{ object = 'v_res_m_sidetable',               price = 2500, label = 'Yan ünite' },
			{ object = 'v_res_son_desk',                  price = 2500, label = 'Masa ünitesi' },
			{ object = 'v_res_tre_bedsidetable',          price = 2500, label = 'Yan ünite' },
			{ object = 'v_res_tre_bedsidetableb',         price = 2500, label = 'Yan ünite 2' },
			{ object = 'v_res_tre_smallbookshelf',        price = 2500, label = 'Kitaplık ünitesi' },
			{ object = 'v_res_tre_storagebox',            price = 2500, label = 'Kutu ünitesi' },
			{ object = 'v_res_tre_storageunit',           price = 2500, label = 'Depolama ünitesi' },
			{ object = 'v_res_tre_wardrobe',              price = 2500, label = 'Gardrop ünitesi' },
			{ object = 'v_res_tre_wdunitscuz',            price = 2500, label = 'Ahşap ünite' },
			{ object = 'prop_devin_box_closed',           price = 100,  label = 'Fasulye torbası 1' },
			{ object = 'prop_mil_crate_01',               price = 100,  label = 'Askeri kasa 1' },
			{ object = 'prop_mil_crate_02',               price = 100,  label = 'Askeri kasa 2' },
			{ object = 'prop_ld_int_safe_01',             price = 1100, label = 'Kasa' },
			{ object = 'prop_toolchest_05',               price = 5000, label = 'Üretim tezgahı' },
			{ object = 'v_corp_filecablow',               price = 500,  label = 'Alçak dosya dolabı' },
			{ object = 'v_corp_filecabtall',              price = 500,  label = 'Yüksek dosya dolabı' },
			{ object = 'apa_mp_h_str_shelffloorm_02',     price = 500,  label = 'Büyük modern dolap' },
			{ object = 'v_ilev_frnkwarddr1',              price = 500,  label = 'Franklin dolabı' },
			{ object = 'prop_coathook_01',                price = 100,  label = 'Portmanto' },
			{ object = 'v_corp_lowcabdark01',             price = 500,  label = 'Alçak siyah dosya dolabı' },
			{ object = 'v_corp_tallcabdark01',            price = 500,  label = 'Yüksek siyah dosya dolabı' },
			{ object = 'v_corp_cabshelves01',             price = 1000, label = 'Siyah dosya dolabı' },
			{ object = 'v_corp_offshelf',                 price = 1000, label = 'Büyük dosya dolabı' },
			{ object = 'v_61_lng_mesh_unitc',             price = 500,  label = 'Beyaz kitaplık' },
			{ object = 'ba_wardrobe',                     price = 500,  label = 'Gardrop' },
			{ object = 'apa_mp_h_str_sideboardl_06',      price = 750,  label = 'Modern dolap' },
			{ object = 'apa_mp_h_str_sideboardl_09',      price = 750,  label = 'Modern dolap 2' },
			{ object = 'apa_mp_h_str_shelfwallm_01',      price = 750,  label = 'Kitaplık 2' },
			{ object = 'apa_mp_h_str_sideboardl_11',      price = 750,  label = 'Modern dolap 3' },
			{ object = 'imp_prop_impexp_parts_rack_03a',  price = 750,  label = 'Araba parçaları' },
			{ object = 'imp_prop_impexp_parts_rack_04a',  price = 750,  label = 'Araba parçaları 2' },
			{ object = 'imp_prop_impexp_parts_rack_05a',  price = 750,  label = 'Araba parçaları 3' },
			{ object = 'apa_mp_h_bed_chestdrawer_02',     price = 750,  label = 'Çekmeceli dolap' },
			{ object = 'hei_heist_bed_chestdrawer_04',    price = 750,  label = 'Çekmeceli dolap 2' },
			{ object = 'prop_rub_cabinet',                price = 50,   label = 'Paslı dosya dolabı' },
			{ object = 'prop_tv_cabinet_03',              price = 750,  label = 'Küçük TV dolabı' },
			{ object = 'prop_tv_cabinet_04',              price = 750,  label = 'Küçük TV dolabı 2' },
			{ object = 'prop_tv_cabinet_05',              price = 750,  label = 'Küçük TV dolabı 3' },
			{ object = 'apa_mp_h_str_shelffreel_01',      price = 750,  label = 'IKEA dolabı' },
			{ object = 'apa_mp_h_str_sideboardl_13',      price = 750,  label = 'Modern dolap 4' },
			{ object = 'apa_mp_h_str_sideboardl_14',      price = 750,  label = 'Modern dolap 5' },
			{ object = 'apa_mp_h_str_sideboardm_02',      price = 750,  label = 'Modern dolap 6' },
			{ object = 'bkr_prop_biker_garage_locker_01', price = 750,  label = 'Biker dolabı' },
			{ object = 'gr_prop_gr_bench_04b',            price = 750,  label = 'Biker tezgahı' }
		},
	},
	electronics = {
		label = 'Elektronik',
		items = {
			{ object = 'prop_trailr_fridge',                price = 300,  label = 'Eski buzdolabı' },
			{ object = 'v_res_fh_speaker',                  price = 300,  label = 'Hoparlör' },
			{ object = 'v_res_fh_speakerdock',              price = 300,  label = 'Hoparlör istasyonu' },
			{ object = 'v_res_fh_bedsideclock',             price = 300,  label = 'Komodin saati' },
			{ object = 'v_res_fa_phone',                    price = 300,  label = 'Telefon' },
			{ object = 'v_res_fh_towerfan',                 price = 300,  label = 'Kule vantilatörü' },
			{ object = 'v_res_fa_fan',                      price = 300,  label = 'Vantilatör' },
			{ object = 'v_res_lest_bigscreen',              price = 300,  label = 'Büyük ekran' },
			{ object = 'v_res_lest_monitor',                price = 300,  label = 'Monitör' },
			{ object = 'v_res_tre_mixer',                   price = 300,  label = 'Mikser' },
			{ object = 'prop_cs_cctv',                      price = 100,  label = 'Güvenlik kamerası' },
			{ object = 'prop_ld_lap_top',                   price = 100,  label = 'Dizüstü bilgisayar' },
			{ object = 'prop_ld_monitor_01',                price = 100,  label = 'Monitör' },
			{ object = 'prop_speaker_05',                   price = 500,  label = 'Duvar hoparlörü' },
			{ object = 'prop_tv_flat_03b',                  price = 1000, label = 'Küçük düz ekran' },
			{ object = 'prop_laptop_01a',                   price = 750,  label = 'Açık dizüstü bilgisayar' },
			{ object = 'prop_tv_flat_michael',              price = 3000, label = 'Asılı düz ekran' },
			{ object = 'prop_dyn_pc',                       price = 1000, label = 'Bilgisayar' },
			{ object = 'prop_keyboard_01b',                 price = 100,  label = 'Klavye' },
			{ object = 'prop_mouse_01b',                    price = 100,  label = 'Bilgisayar faresi' },
			{ object = 'v_ret_gc_phone',                    price = 100,  label = 'Ofis telefonu' },
			{ object = 'prop_tv_flat_01',                   price = 5000, label = 'Büyük düz ekran' },
			{ object = 'prop_arcade_01',                    price = 5000, label = 'Arcade makinesi' },
			{ object = 'prop_console_01',                   price = 250,  label = 'Oyun konsolu' },
			{ object = 'v_res_tre_dvdplayer',               price = 250,  label = 'DVD oynatıcı' },
			{ object = 'prop_speaker_08',                   price = 500,  label = 'Ahşap hoparlör' },
			{ object = 'prop_cctv_mon_02',                  price = 300,  label = 'Güvenlik monitörü' },
			{ object = 'prop_tv_flat_02',                   price = 2500, label = 'Ayaklı düz ekran' },
			{ object = 'prop_cctv_cam_01a',                 price = 300,  label = 'Güvenlik kamerası 2' },
			{ object = 'prop_dest_cctv_02',                 price = 300,  label = 'Güvenlik monitörü 2' },
			{ object = 'prop_cctv_cam_07a',                 price = 300,  label = 'Güvenlik kamerası 3' },
			{ object = 'apa_mp_h_str_avunits_04',           price = 5500, label = 'Düz ekran mobilyası' },
			{ object = 'apa_mp_h_str_avunits_01',           price = 5500, label = 'Düz ekran mobilyası 2' },
			{ object = 'v_club_vu_deckcase',                price = 1000, label = 'DJ seti' },
			{ object = 'v_corp_servercln',                  price = 1000, label = 'Sunucu rafı' },
			{ object = 'apa_mp_h_str_avunitl_01_b',         price = 5500, label = 'Düz ekran mobilyası 3' },
			{ object = 'apa_mp_h_str_avunitl_04',           price = 5500, label = 'Düz ekran mobilyası 4' },
			{ object = 'apa_mp_h_str_avunitm_01',           price = 5500, label = 'Düz ekran mobilyası 5' },
			{ object = 'apa_mp_h_str_avunitm_03',           price = 5500, label = 'Düz ekran mobilyası 6' },
			{ object = 'apa_mp_h_str_avunits_04',           price = 5500, label = 'Düz ekran mobilyası 7' },
			{ object = 'v_res_printer',                     price = 300,  label = 'Yazıcı' },
			{ object = 'apa_mp_h_acc_phone_01',             price = 100,  label = 'Eski tip telefon' },
			{ object = 'v_res_mousemat',                    price = 300,  label = 'Mouse pad' },
			{ object = 'v_res_pcheadset',                   price = 300,  label = 'Kulaklık' },
			{ object = 'v_res_pcspeaker',                   price = 300,  label = 'PC hoparlörü' },
			{ object = 'ba_prop_battle_club_speaker_small', price = 500,  label = 'Küçük kutu' },
			{ object = 'ba_prop_battle_club_speaker_med',   price = 750,  label = 'Kutu' },
			{ object = 'ba_prop_battle_club_speaker_large', price = 1000, label = 'Büyük kutu' },
			{ object = 'v_res_pcspeaker',                   price = 300,  label = 'PC hoparlörü' },
			{ object = 'v_res_pcwoofer',                    price = 300,  label = 'PC subwoofer' },
			{ object = 'prop_controller_01',                price = 300,  label = 'Kumanda' },
			{ object = 'prop_cs_remote_01',                 price = 300,  label = 'Uzaktan kumanda' },
			{ object = 'prop_portable_hifi_01',             price = 300,  label = 'Radyo' },
			{ object = 'prop_dj_deck_02',                   price = 300,  label = 'DJ masası' },
			{ object = 'prop_speaker_01',                   price = 300,  label = 'Hoparlör' }
		},
	},
	lighting = {
		label = 'Aydınlatma',
		items = {
			{ object = 'v_corp_cd_desklamp',                price = 100, label = 'Masa lambası (Corp)' },
			{ object = 'v_res_desklamp',                    price = 100, label = 'Masa lambası' },
			{ object = 'v_res_d_lampa',                     price = 100, label = 'Lamba AA' },
			{ object = 'v_res_fa_lamp1on',                  price = 100, label = 'Lamba 1' },
			{ object = 'v_res_fh_floorlamp',                price = 100, label = 'Ayaklı lamba' },
			{ object = 'v_res_fh_lampa_on',                 price = 100, label = 'Lamba 2' },
			{ object = 'v_res_j_tablelamp1',                price = 100, label = 'Masa lambası' },
			{ object = 'v_res_j_tablelamp2',                price = 100, label = 'Masa lambası 2' },
			{ object = 'v_res_mdbedlamp',                   price = 100, label = 'Yatak lambası' },
			{ object = 'v_res_mplanttongue',                price = 100, label = 'Bitki lambası' },
			{ object = 'v_res_mtblelampmod',                price = 100, label = 'Masa lambası 3' },
			{ object = 'v_res_m_lampstand',                 price = 100, label = 'Lambader' },
			{ object = 'v_res_m_lampstand2',                price = 100, label = 'Lambader 2' },
			{ object = 'v_res_m_lamptbl',                   price = 100, label = 'Masa lambası 4' },
			{ object = 'v_res_tre_lightfan',                price = 100, label = 'Aydınlatmalı vantilatör' },
			{ object = 'v_res_tre_talllamp',                price = 100, label = 'Uzun lamba' },
			{ object = 'v_ret_fh_walllighton',              price = 100, label = 'Duvar lambası' },
			{ object = 'v_ret_gc_lamp',                     price = 100, label = 'GC lamba' },
			{ object = 'prop_dummy_light',                  price = 100, label = 'Titreyen ışık' },
			{ object = 'prop_ld_cont_light_01',             price = 100, label = 'Yan duvar lambası' },
			{ object = 'V_44_D_emis',                       price = 100, label = 'Test lambası' },
			{ object = 'prop_wall_light_07a',               price = 100, label = 'Fener' },
			{ object = 'prop_wall_light_01a',               price = 100, label = 'Ucuz lamba' },
			{ object = 'v_serv_tu_light2_',                 price = 100, label = 'Endüstriyel ışık' },
			{ object = 'v_serv_tu_light3_',                 price = 100, label = 'Endüstriyel ışık 2' },
			{ object = 'ba_prop_battle_lights_ceiling_l_a', price = 300, label = 'Asma lamba' },
			{ object = 'v_med_p_floorlamp',                 price = 300, label = 'Büyük lamba' },
			{ object = 'v_club_vu_lamp',                    price = 100, label = 'İnce lamba' },
			{ object = 'ba_prop_battle_lights_wall_l_a',    price = 100, label = 'Duvar lambası' },
			{ object = 'ba_prop_battle_lights_ceiling_l_c', price = 300, label = 'Asma lamba 2' },
			{ object = 'ba_prop_battle_lights_ceiling_l_b', price = 300, label = 'Avize 2' },
			{ object = 'ba_prop_battle_lights_wall_l_c',    price = 100, label = 'Duvar lambası 2' },
			{ object = 'ba_prop_battle_lights_wall_l_b',    price = 100, label = 'Duvar lambası 3' },
			{ object = 'hei_heist_lit_lightpendant_02',     price = 300, label = 'Asma lamba 3' },
			{ object = 'prop_oldlight_01b',                 price = 100, label = 'Duvar lambası 4' },
			{ object = 'apa_mp_h_lit_floorlampnight_07',    price = 100, label = 'Mavi lamba' },
			{ object = 'apa_mp_h_ceiling_light_01',         price = 100, label = 'Ticari lamba' },
			{ object = 'apa_mp_h_ceiling_light_01_day',     price = 100, label = 'Ticari lamba 2' },
			{ object = 'apa_mp_h_ceiling_light_02',         price = 100, label = 'Tavan lambası' },
			{ object = 'apa_mp_h_ceiling_light_02_day',     price = 100, label = 'Tavan lambası 2' },
			{ object = 'ba_prop_battle_lights_ceiling_l_d', price = 100, label = 'Ticari lamba 3' },
			{ object = 'ba_prop_battle_lights_ceiling_l_f', price = 100, label = 'Tavan lambası 3' },
			{ object = 'ba_prop_battle_lights_ceiling_l_e', price = 100, label = 'Tavan lambası 4' },
			{ object = 'apa_mp_h_floorlamp_a',              price = 100, label = 'Ayaklı lamba' },
			{ object = 'apa_mp_h_floorlamp_b',              price = 100, label = 'Ayaklı lamba 2' },
			{ object = 'apa_mp_h_floorlamp_c',              price = 100, label = 'Ayaklı lamba 3' },
			{ object = 'apa_mp_h_floor_lamp_int_08',        price = 100, label = 'Ayaklı lamba 4' },
			{ object = 'apa_mp_h_lampbulb_multiple_a',      price = 100, label = 'Tavan lambası 5' },
			{ object = 'apa_mp_h_lit_floorlamp_02',         price = 100, label = 'Ayaklı lamba 5' },
			{ object = 'apa_mp_h_lit_floorlampnight_14',    price = 100, label = 'Ayaklı lamba 6' },
			{ object = 'apa_mp_h_lit_floorlamp_03',         price = 100, label = 'Ayaklı lamba 7' },
			{ object = 'apa_mp_h_lit_floorlamp_06',         price = 100, label = 'Ayaklı lamba 8' },
			{ object = 'apa_mp_h_lit_floorlamp_10',         price = 100, label = 'Ayaklı lamba 9' },
			{ object = 'apa_mp_h_lit_floorlamp_13',         price = 100, label = 'Ayaklı lamba 10' },
			{ object = 'apa_mp_h_lit_floorlamp_17',         price = 100, label = 'Ayaklı lamba 11' },
			{ object = 'apa_mp_h_lit_lamptablenight_16',    price = 100, label = 'Gece lambası' },
			{ object = 'apa_mp_h_lit_lamptablenight_24',    price = 100, label = 'Gece lambası 2' },
			{ object = 'apa_mp_h_lit_lamptable_005',        price = 100, label = 'Gece lambası 3' },
			{ object = 'apa_mp_h_lit_lamptable_04',         price = 100, label = 'Gece lambası 4' },
			{ object = 'apa_mp_h_lit_lamptable_09',         price = 100, label = 'Gece lambası 5' },
			{ object = 'apa_mp_h_lit_lamptable_14',         price = 100, label = 'Gece lambası 6' },
			{ object = 'apa_mp_h_lit_lamptable_17',         price = 100, label = 'Gece lambası 7' },
			{ object = 'apa_mp_h_yacht_table_lamp_01',      price = 100, label = 'Gece lambası 8' }
		},
	},
	tables = {
		label = 'Masalar',
		items = {
			{ object = 'v_res_d_coffeetable',            price = 500,  label = 'Sehpa 1' },
			{ object = 'v_res_d_roundtable',             price = 500,  label = 'Yuvarlak masa' },
			{ object = 'v_res_d_smallsidetable',         price = 500,  label = 'Küçük yan sehpa' },
			{ object = 'v_res_fh_coftablea',             price = 500,  label = 'Masa A' },
			{ object = 'v_res_fh_coftableb',             price = 500,  label = 'Masa B' },
			{ object = 'v_res_fh_coftbldisp',            price = 500,  label = 'Masa C' },
			{ object = 'v_res_fh_diningtable',           price = 500,  label = 'Yemek masası' },
			{ object = 'v_res_j_coffeetable',            price = 500,  label = 'Sehpa 2' },
			{ object = 'v_res_j_lowtable',               price = 500,  label = 'Alçak masa' },
			{ object = 'v_res_mdbedtable',               price = 500,  label = 'Yatak sehpası' },
			{ object = 'v_res_mddesk',                   price = 500,  label = 'Masa' },
			{ object = 'v_res_msidetblemod',             price = 500,  label = 'Yan sehpa' },
			{ object = 'v_res_m_console',                price = 500,  label = 'Konsol masa' },
			{ object = 'v_res_m_dinetble_replace',       price = 500,  label = 'Yemek masası 2' },
			{ object = 'v_res_m_h_console',              price = 500,  label = 'Konsol H masası' },
			{ object = 'v_res_m_stool',                  price = 500,  label = 'Tabure?' },
			{ object = 'v_res_tre_sideboard',            price = 500,  label = 'Konsol masa' },
			{ object = 'v_res_tre_table2',               price = 500,  label = 'Masa 2' },
			{ object = 'v_res_tre_tvstand',              price = 500,  label = 'TV sehpası' },
			{ object = 'v_res_tre_tvstand_tall',         price = 500,  label = 'Yüksek TV sehpası' },
			{ object = 'v_med_p_coffeetable',            price = 500,  label = 'Med sehpa' },
			{ object = 'v_med_p_desk',                   price = 500,  label = 'Med masa' },
			{ object = 'prop_yacht_table_01',            price = 100,  label = 'Yat masası 1' },
			{ object = 'prop_yacht_table_02',            price = 100,  label = 'Yat masası 2' },
			{ object = 'prop_yacht_table_03',            price = 100,  label = 'Yat masası 3' },
			{ object = 'v_ret_csr_table',                price = 100,  label = 'CSR masa' },
			{ object = 'v_res_mconsoletrad',             price = 250,  label = 'Yüksek yan sehpa' },
			{ object = 'v_ilev_liconftable_sml',         price = 500,  label = 'Ofis masası' },
			{ object = 'v_ret_tablesml',                 price = 350,  label = 'Marillaux yan sehpa' },
			{ object = 'apa_mp_h_yacht_coffee_table_02', price = 500,  label = 'Kahverengi sehpa' },
			{ object = 'apa_mp_h_yacht_side_table_01',   price = 300,  label = 'Kahverengi yan sehpa' },
			{ object = 'apa_mp_h_yacht_side_table_02',   price = 300,  label = 'Yuvarlak yan sehpa' },
			{ object = 'apa_mp_h_tab_sidelrg_04',        price = 300,  label = 'Yuvarlak yan sehpa 2' },
			{ object = 'v_club_vu_table',                price = 300,  label = 'Örtülü masa' },
			{ object = 'apa_mp_h_tab_sidelrg_07',        price = 500,  label = 'Cam sehpa' },
			{ object = 'bkr_prop_weed_table_01b',        price = 100,  label = 'Katlanır masa' },
			{ object = 'ba_prop_int_trad_table',         price = 300,  label = 'Ayaklı masa' },
			{ object = 'apa_mp_h_str_sideboards_02',     price = 750,  label = 'Cam yan sehpa' },
			{ object = 'apa_mp_h_yacht_coffee_table_01', price = 750,  label = 'Modern sehpa' },
			{ object = 'apa_mp_h_din_table_04',          price = 1000, label = 'Cam yemek masası' },
			{ object = 'xm_prop_base_staff_desk_01',     price = 5000, label = 'Masa + kurulum' },
			{ object = 'apa_mp_h_tab_coffee_07',         price = 1000, label = 'Üçgen yan sehpa' },
			{ object = 'apa_mp_h_tab_coffee_08',         price = 1000, label = 'Beyaz yan sehpa' },
			{ object = 'apa_mp_h_tab_sidelrg_01',        price = 1000, label = 'Cam yan sehpa' },
			{ object = 'apa_mp_h_tab_sidelrg_02',        price = 1000, label = 'Cam yan sehpa 2' },
			{ object = 'apa_mp_h_tab_sidesml_01',        price = 1000, label = 'Katlanır masa' },
			{ object = 'ba_prop_int_edgy_table_01',      price = 500,  label = 'Mermer masa' },
			{ object = 'ba_prop_int_edgy_table_02',      price = 500,  label = 'Yüksek mermer masa' },
			{ object = 'apa_mp_h_tab_sidelrg_01',        price = 1000, label = 'Cam yan sehpa' },
			{ object = 'xm_prop_lab_desk_01',            price = 1000, label = 'Laboratuvar masası' }
		},
	},
	plants = {
		label = 'Bitkiler',
		items = {
			{ object = 'prop_fib_plant_01',            price = 150, label = 'Bitki Fib' },
			{ object = 'v_corp_bombplant',             price = 170, label = 'Bitki Bomb' },
			{ object = 'v_res_mflowers',               price = 170, label = 'Çiçekli bitki' },
			{ object = 'v_res_mvasechinese',           price = 170, label = 'Çin bitkisi' },
			{ object = 'v_res_m_bananaplant',          price = 170, label = 'Muz bitkisi' },
			{ object = 'v_res_m_palmplant1',           price = 170, label = 'Palmiye' },
			{ object = 'v_res_m_palmstairs',           price = 170, label = 'Palmiye 2' },
			{ object = 'v_res_m_urn',                  price = 170, label = 'Saksı bitkisi' },
			{ object = 'v_res_rubberplant',            price = 170, label = 'Kauçuk bitkisi' },
			{ object = 'v_res_tre_plant',              price = 170, label = 'Bitki' },
			{ object = 'v_res_tre_tree',               price = 170, label = 'Ağaç' },
			{ object = 'v_med_p_planter',              price = 170, label = 'Saksı' },
			{ object = 'v_ret_flowers',                price = 100, label = 'Çiçekler' },
			{ object = 'v_ret_j_flowerdisp',           price = 100, label = 'Çiçekler 1' },
			{ object = 'v_ret_j_flowerdisp_white',     price = 100, label = 'Çiçekler 2' },
			{ object = 'v_res_m_vasefresh',            price = 300, label = 'Çiçekli vazo' },
			{ object = 'v_res_rosevasedead',           price = 300, label = 'Pembe vazo 2' },
			{ object = 'v_res_exoticvase',             price = 300, label = 'Çiçekli vazo 2' },
			{ object = 'v_res_rosevase',               price = 300, label = 'Pembe vazo' },
			{ object = 'prop_pot_plant_6a',            price = 300, label = 'Asılı bitki' },
			{ object = 'prop_pot_plant_02a',           price = 300, label = 'Saksı' },
			{ object = 'apa_mp_h_acc_plant_palm_01',   price = 300, label = 'Palmiye bitkisi' },
			{ object = 'prop_plant_interior_05a',      price = 300, label = 'Çiçek kutusu' },
			{ object = 'prop_plant_int_01a',           price = 300, label = 'Bitki' },
			{ object = 'prop_plant_int_01b',           price = 300, label = 'Bitki 2' },
			{ object = 'prop_plant_int_02a',           price = 300, label = 'Bitki 3' },
			{ object = 'prop_plant_int_02b',           price = 300, label = 'Bitki 4' },
			{ object = 'prop_plant_int_03a',           price = 300, label = 'Bitki 5' },
			{ object = 'prop_plant_int_03b',           price = 300, label = 'Bitki 6' },
			{ object = 'prop_plant_int_03c',           price = 300, label = 'Bitki 7' },
			{ object = 'prop_plant_int_04a',           price = 300, label = 'Bitki 8' },
			{ object = 'prop_plant_int_04c',           price = 300, label = 'Bitki 9' },
			{ object = 'prop_plant_int_05b',           price = 300, label = 'Çiçek kutusu 2' },
			{ object = 'prop_pot_plant_01a',           price = 300, label = 'Saksı 2' },
			{ object = 'prop_pot_plant_01b',           price = 300, label = 'Saksı 3' },
			{ object = 'prop_pot_plant_01c',           price = 300, label = 'Saksı 4' },
			{ object = 'prop_pot_plant_01d',           price = 300, label = 'Saksı 5' },
			{ object = 'prop_pot_plant_01e',           price = 300, label = 'Saksı 6' },
			{ object = 'prop_pot_plant_03b',           price = 300, label = 'Saksı 7' },
			{ object = 'prop_pot_plant_05a',           price = 300, label = 'Saksı 8' },
			{ object = 'prop_pot_plant_05b',           price = 300, label = 'Saksı 9' },
			{ object = 'p_int_jewel_plant_01',         price = 300, label = 'Saksı 10' },
			{ object = 'p_int_jewel_plant_02',         price = 300, label = 'Saksı 11' },
			{ object = 'apa_mp_h_acc_vase_flowers_01', price = 300, label = 'Saksı 12' },
			{ object = 'apa_mp_h_acc_vase_flowers_02', price = 300, label = 'Saksı 13' },
			{ object = 'apa_mp_h_acc_vase_flowers_03', price = 300, label = 'Saksı 14' },
			{ object = 'apa_mp_h_acc_vase_flowers_04', price = 300, label = 'Saksı 15' }
		},
	},
	kitchen = {
		label = 'Mutfak',
		items = {
			{ object = 'prop_washer_01',                price = 150,  label = 'Çamaşır makinesi 1' },
			{ object = 'prop_washer_02',                price = 150,  label = 'Çamaşır makinesi 2' },
			{ object = 'prop_washer_03',                price = 150,  label = 'Çamaşır makinesi 3' },
			{ object = 'prop_washing_basket_01',        price = 150,  label = 'Çamaşır sepeti' },
			{ object = 'v_res_fridgemoda',              price = 150,  label = 'Buzdolabı 1' },
			{ object = 'v_res_fridgemodsml',            price = 150,  label = 'Buzdolabı 2' },
			{ object = 'prop_fridge_01',                price = 150,  label = 'Buzdolabı 3' },
			{ object = 'prop_fridge_03',                price = 150,  label = 'Buzdolabı 4' },
			{ object = 'prop_cooker_03',                price = 150,  label = 'Ocak' },
			{ object = 'prop_micro_01',                 price = 150,  label = 'Mikrodalga 1' },
			{ object = 'prop_micro_02',                 price = 150,  label = 'Mikrodalga 2' },
			{ object = 'prop_wok',                      price = 150,  label = 'Wok' },
			{ object = 'v_res_cakedome',                price = 150,  label = 'Pasta tabağı' },
			{ object = 'v_res_fa_chopbrd',              price = 150,  label = 'Kesme tahtası' },
			{ object = 'v_res_mutensils',               price = 150,  label = 'Mutfak gereçleri' },
			{ object = 'v_res_pestle',                  price = 150,  label = 'Havan' },
			{ object = 'v_ret_ta_paproll',              price = 150,  label = 'Kağıt havlu 1' },
			{ object = 'v_ret_ta_paproll2',             price = 150,  label = 'Kağıt havlu 2' },
			{ object = 'v_ret_fh_pot01',                price = 150,  label = 'Tencere 1' },
			{ object = 'v_ret_fh_pot02',                price = 150,  label = 'Tencere 2' },
			{ object = 'v_ret_fh_pot05',                price = 150,  label = 'Tencere 3' },
			{ object = 'prop_pot_03',                   price = 150,  label = 'Tencere 4' },
			{ object = 'prop_pot_04',                   price = 150,  label = 'Tencere 5' },
			{ object = 'prop_pot_05',                   price = 150,  label = 'Tencere 6' },
			{ object = 'prop_pot_06',                   price = 150,  label = 'Tencere 7' },
			{ object = 'prop_pot_rack',                 price = 150,  label = 'Tencere rafı' },
			{ object = 'prop_kitch_juicer',             price = 150,  label = 'Meyve sıkacağı' },
			{ object = 'v_res_ovenhobmod',              price = 1000, label = 'Ocak' },
			{ object = 'v_res_mkniferack',              price = 100,  label = 'Bıçak' },
			{ object = 'v_res_mchopboard',              price = 100,  label = 'Kesme tahtası' },
			{ object = 'prop_cs_kitchen_cab_l',         price = 750,  label = 'Geniş mutfak dolabı' },
			{ object = 'prop_cs_kitchen_cab_r',         price = 500,  label = 'Küçük mutfak dolabı' },
			{ object = 'prop_cs_kitchen_cab_r',         price = 500,  label = 'Küçük mutfak dolabı' },
			{ object = 'v_res_tre_fridge',              price = 500,  label = 'Buzdolabı' },
			{ object = 'apa_mp_h_acc_coffeemachine_01', price = 500,  label = 'Kahve makinesi' },
			{ object = 'p_new_j_counter_02',            price = 500,  label = 'Tezgah' },
			{ object = 'prop_bar_pump_09',              price = 500,  label = 'Pompa 1' },
			{ object = 'prop_bar_pump_01',              price = 500,  label = 'Pompa 2' },
			{ object = 'prop_chip_fryer',               price = 500,  label = 'Patates kızartma makinesi' },
			{ object = 'prop_cleaver',                  price = 500,  label = 'Bıçak' },
			{ object = 'prop_coffee_mac_02',            price = 500,  label = 'Kahve makinesi' },
			{ object = 'prop_coffee_mac_01',            price = 500,  label = 'Kahve makinesi 2' },
			{ object = 'prop_cs_fork',                  price = 500,  label = 'Çatal' },
			{ object = 'prop_cs_sink_filler',           price = 500,  label = 'Musluk' },
			{ object = 'prop_toaster_01',               price = 500,  label = 'Tost makinesi' },
			{ object = 'prop_cs_plate_01',              price = 500,  label = 'Tabak' },
			{ object = 'prop_foodprocess_01',           price = 500,  label = 'Mutfak robotu' },
			{ object = 'prop_food_sugarjar',            price = 500,  label = 'Şekerlik' },
			{ object = 'prop_juice_dispenser',          price = 500,  label = 'Dispenser' },
			{ object = 'prop_knife_stand',              price = 500,  label = 'Bıçaklık' },
			{ object = 'prop_knife',                    price = 500,  label = 'Bıçak 2' },
			{ object = 'prop_micro_04',                 price = 500,  label = 'Mikrodalga 4' },
			{ object = 'v_ret_fh_plate3',               price = 500,  label = 'Tabak 5' },
			{ object = 'v_ilev_tt_plate01',             price = 500,  label = 'Tabak 6' },
			{ object = 'v_res_fa_grater',               price = 500,  label = 'Rende' },
			{ object = 'v_res_tt_pizzaplate',           price = 500,  label = 'Pizza tabağı' },
			{ object = 'v_ret_247_ketchup2',            price = 500,  label = 'Ketçap' }
		},
	},
	bathroom = {
		label = 'Banyo',
		items = {
			{ object = 'prop_ld_toilet_01',    price = 100,  label = 'Tuvalet 1' },
			{ object = 'prop_toilet_01',       price = 100,  label = 'Tuvalet 2' },
			{ object = 'prop_toilet_02',       price = 100,  label = 'Tuvalet 3' },
			{ object = 'prop_sink_02',         price = 100,  label = 'Lavabo 1' },
			{ object = 'prop_sink_04',         price = 100,  label = 'Lavabo 2' },
			{ object = 'prop_sink_05',         price = 100,  label = 'Lavabo 3' },
			{ object = 'prop_sink_06',         price = 100,  label = 'Lavabo 4' },
			{ object = 'prop_soap_disp_01',    price = 100,  label = 'Sabunluk' },
			{ object = 'prop_shower_rack_01',  price = 100,  label = 'Duş rafı' },
			{ object = 'prop_handdry_01',      price = 100,  label = 'El kurutma makinesi 1' },
			{ object = 'prop_handdry_02',      price = 100,  label = 'El kurutma makinesi 2' },
			{ object = 'prop_towel_rail_01',   price = 100,  label = 'Havlu askısı 1' },
			{ object = 'prop_towel_rail_02',   price = 100,  label = 'Havlu askısı 2' },
			{ object = 'prop_towel_01',        price = 100,  label = 'Havlu 1' },
			{ object = 'v_res_mbtowel',        price = 100,  label = 'Havlu 2' },
			{ object = 'v_res_mbtowelfld',     price = 100,  label = 'Havlu 3' },
			{ object = 'v_res_mbath',          price = 100,  label = 'Küvet' },
			{ object = 'v_res_mbsink',         price = 100,  label = 'Lavabo' },
			{ object = 'v_ilev_mm_faucet',     price = 100,  label = 'Musluk' },
			{ object = 'v_res_tre_washbasket', price = 250,  label = 'Çamaşır sepeti' },
			{ object = 'prop_toilet_soap_02',  price = 100,  label = 'Sabun tepsisi' },
			{ object = 'prop_bar_sink_01',     price = 100,  label = 'Lavabo' },
			{ object = 'apa_mp_h_bathtub_01',  price = 1000, label = 'Küvet' },
			{ object = 'prop_toilet_brush_01', price = 1000, label = 'Fırça' },
			{ object = 'prop_toilet_roll_01',  price = 1000, label = 'Tuvalet kağıdı' },
			{ object = 'prop_toilet_roll_02',  price = 1000, label = 'Tuvalet kağıdı 2' },
			{ object = 'prop_toilet_shamp_01', price = 1000, label = 'Şampuan' },
			{ object = 'prop_toilet_shamp_02', price = 1000, label = 'Şampuan 2' }
		},
	},
	medical = {
		label = 'Tıbbi',
		items = {
			{ object = 'v_med_barrel',             price = 750, label = 'Varil' },
			{ object = 'v_med_apecrate',           price = 750, label = 'Ape kasası' },
			{ object = 'v_med_apecratelrg',        price = 750, label = 'Büyük Ape kasası' },
			{ object = 'v_med_bed1',               price = 750, label = 'Yatak 1' },
			{ object = 'v_med_bed2',               price = 750, label = 'Yatak 2' },
			{ object = 'v_med_bedtable',           price = 750, label = 'Yatak sehpası' },
			{ object = 'v_med_bench1',             price = 750, label = 'Bank 1' },
			{ object = 'v_med_bench2',             price = 750, label = 'Bank 2' },
			{ object = 'v_med_benchcentr',         price = 750, label = 'Orta bank' },
			{ object = 'v_med_benchset1',          price = 750, label = 'Bank seti' },
			{ object = 'v_med_bigtable',           price = 750, label = 'Büyük masa' },
			{ object = 'v_med_bin',                price = 150, label = 'Çöp kutusu' },
			{ object = 'v_med_centrifuge1',        price = 750, label = 'Santrifüj' },
			{ object = 'v_med_cooler',             price = 750, label = 'Soğutucu' },
			{ object = 'v_med_cor_ceilingmonitor', price = 750, label = 'Monitör' },
			{ object = 'v_med_cor_autopsytbl',     price = 750, label = 'Otopsi masası' },
			{ object = 'v_med_cor_cembin',         price = 750, label = 'Çöp kutusu' },
			{ object = 'v_med_cor_cemtrolly2',     price = 750, label = 'Araba' },
			{ object = 'v_med_cor_chemical',       price = 750, label = 'Kimyasal' },
			{ object = 'v_med_cor_emblmtable',     price = 750, label = 'BLM masası' },
			{ object = 'v_med_cor_fileboxa',       price = 750, label = 'Dosya kutusu' },
			{ object = 'v_med_cor_filingcab',      price = 750, label = 'Dosya dolabı' },
			{ object = 'v_med_cor_hose',           price = 750, label = 'Hortum' },
			{ object = 'v_med_cor_largecupboard',  price = 750, label = 'Büyük dolap' },
			{ object = 'v_med_cor_lightbox',       price = 750, label = 'Işık kutusu' },
			{ object = 'v_med_cor_medstool',       price = 750, label = 'Tıbbi tabure' },
			{ object = 'v_med_cor_minifridge',     price = 750, label = 'Mini buzdolabı' },
			{ object = 'v_med_cor_papertowels',    price = 750, label = 'Kağıt havlu' },
			{ object = 'v_med_cor_photocopy',      price = 750, label = 'Fotokopi makinesi' },
			{ object = 'v_med_cor_tvstand',        price = 750, label = 'TV sehpası' },
			{ object = 'v_med_cor_wallunita',      price = 750, label = 'Duvar ünitesi' },
			{ object = 'v_med_examlight',          price = 750, label = 'Muayene lambası' },
			{ object = 'v_med_gastank',            price = 750, label = 'Gaz tankı' },
			{ object = 'v_med_hazmatscan',         price = 750, label = 'Tehlikeli madde tarayıcısı' },
			{ object = 'v_med_hospheadwall1',      price = 750, label = 'Baş duvar ünitesi' },
			{ object = 'v_med_hospseating1',       price = 750, label = 'Oturma alanı' },
			{ object = 'v_med_hosptable',          price = 750, label = 'Hastane masası' },
			{ object = 'v_med_latexgloveboxblue',  price = 50,  label = 'Eldiven kutusu' },
			{ object = 'v_med_medwastebin',        price = 750, label = 'Çöp kutusu' },
			{ object = 'v_med_oscillator3',        price = 750, label = 'Osilatör' },
			{ object = 'prop_ld_health_pack',      price = 100, label = 'Sağlık paketi' },
		},
	},
	walldecoration = {
		label = 'Duvar Dekoru',
		items = {
			{ object = 'apa_p_h_acc_artwalll_02',      price = 1000, label = 'İzli tablo' },
			{ object = 'v_ind_cs_toolboard',           price = 500,  label = 'Aletler' },
			{ object = 'apa_mp_stilts_bed_art',        price = 300,  label = '3D sanat' },
			{ object = 'ex_office_swag_paintings03',   price = 1000, label = 'Yer tablosu' },
			{ object = 'ex_mp_h_acc_artwallm_03',      price = 750,  label = 'Soyut tablo' },
			{ object = 'ex_p_h_acc_artwallm_04',       price = 750,  label = 'Soyut tablo 2' },
			{ object = 'ex_p_h_acc_artwalll_01',       price = 1250, label = 'Büyük soyut tablo' },
			{ object = 'apa_p_h_acc_artwalll_03',      price = 750,  label = 'Soyut tablo 3' },
			{ object = 'ex_mp_h_acc_artwallm_02',      price = 750,  label = 'Soyut tablo 4' },
			{ object = 'ex_p_h_acc_artwallm_03',       price = 750,  label = 'Soyut tablo 5' },
			{ object = 'apa_mp_stilts_a_study_pics',   price = 500,  label = 'Tablolar' },
			{ object = 'apa_mp_h_acc_artwallm_02',     price = 750,  label = 'Soyut tablo 6' },
			{ object = 'apa_mp_h_acc_artwalll_02',     price = 750,  label = 'Soyut tablo 7' },
			{ object = 'apa_mp_h_acc_artwallm_04',     price = 750,  label = 'Soyut tablo 8' },
			{ object = 'prop_dart_bd_cab_01',          price = 250,  label = 'Dart tahtası' },
			{ object = 'prop_dart_bd_01',              price = 250,  label = 'Dart tahtası 2' },
			{ object = 'hei_heist_acc_artwalll_01',    price = 250,  label = 'Duvar dekoru 1' },
			{ object = 'hei_heist_acc_artgolddisc_01', price = 250,  label = 'Duvar dekoru 2' },
			{ object = 'hei_heist_acc_artgolddisc_02', price = 250,  label = 'Duvar dekoru 3' },
			{ object = 'hei_heist_acc_artgolddisc_03', price = 250,  label = 'Duvar dekoru 4' },
			{ object = 'hei_heist_acc_artgolddisc_04', price = 250,  label = 'Duvar dekoru 5' },
			{ object = 'v_ilev_ra_doorsafe',           price = 250,  label = 'Lüks dekor' }
		},
	},
}
